<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountiesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('counties')->insert([
            ['id' => 1, 'name' => 'آبادان', 'province_id' => 13, 'amar_code' => '601'],
            ['id' => 2, 'name' => 'آباده', 'province_id' => 17, 'amar_code' => '701'],
            ['id' => 3, 'name' => 'آبدانان', 'province_id' => 6, 'amar_code' => '1606'],
            ['id' => 4, 'name' => 'آبیک', 'province_id' => 18, 'amar_code' => '2604'],
            ['id' => 5, 'name' => 'آذرشهر', 'province_id' => 1, 'amar_code' => '321'],
            ['id' => 6, 'name' => 'آرادان', 'province_id' => 15, 'amar_code' => '2006'],
            ['id' => 7, 'name' => 'آران وبیدگل', 'province_id' => 4, 'amar_code' => '1018'],
            ['id' => 8, 'name' => 'آزادشهر', 'province_id' => 24, 'amar_code' => '2710'],
            ['id' => 9, 'name' => 'آستارا', 'province_id' => 25, 'amar_code' => '101'],
            ['id' => 10, 'name' => 'آستانه اشرفیه', 'province_id' => 25, 'amar_code' => '102'],
            ['id' => 11, 'name' => 'آشتیان', 'province_id' => 28, 'amar_code' => '2'],
            ['id' => 12, 'name' => 'آغاجاری', 'province_id' => 13, 'amar_code' => '626'],
            ['id' => 13, 'name' => 'آق قلا', 'province_id' => 24, 'amar_code' => '2708'],
            ['id' => 14, 'name' => 'آمل', 'province_id' => 27, 'amar_code' => '201'],
            ['id' => 15, 'name' => 'آوج', 'province_id' => 18, 'amar_code' => '2606'],
            ['id' => 16, 'name' => 'ابرکوه', 'province_id' => 31, 'amar_code' => '2107'],
            ['id' => 17, 'name' => 'ابوموسی', 'province_id' => 29, 'amar_code' => '2201'],
            ['id' => 18, 'name' => 'ابهر', 'province_id' => 14, 'amar_code' => '1901'],
            ['id' => 19, 'name' => 'اراک', 'province_id' => 28, 'amar_code' => '1'],
            ['id' => 20, 'name' => 'اردبیل', 'province_id' => 3, 'amar_code' => '2401'],
            ['id' => 21, 'name' => 'اردستان', 'province_id' => 4, 'amar_code' => '1001'],
            ['id' => 22, 'name' => 'اردکان', 'province_id' => 31, 'amar_code' => '2101'],
            ['id' => 23, 'name' => 'اردل', 'province_id' => 9, 'amar_code' => '1405'],
            ['id' => 24, 'name' => 'ارزوییه', 'province_id' => 21, 'amar_code' => '823'],
            ['id' => 25, 'name' => 'ارسنجان', 'province_id' => 17, 'amar_code' => '717'],
            ['id' => 26, 'name' => 'ارومیه', 'province_id' => 2, 'amar_code' => '401'],
            ['id' => 27, 'name' => 'ازنا', 'province_id' => 26, 'amar_code' => '1507'],
            ['id' => 28, 'name' => 'استهبان', 'province_id' => 17, 'amar_code' => '702'],
            ['id' => 29, 'name' => 'اسدآباد', 'province_id' => 30, 'amar_code' => '1306'],
            ['id' => 30, 'name' => 'اسفراین', 'province_id' => 12, 'amar_code' => '2801'],
            ['id' => 31, 'name' => 'اسکو', 'province_id' => 1, 'amar_code' => '322'],
            ['id' => 32, 'name' => 'اسلام آبادغرب', 'province_id' => 22, 'amar_code' => '501'],
            ['id' => 33, 'name' => 'اسلامشهر', 'province_id' => 8, 'amar_code' => '2310'],
            ['id' => 34, 'name' => 'اشتهارد', 'province_id' => 5, 'amar_code' => '3005'],
            ['id' => 35, 'name' => 'اشکذر', 'province_id' => 31, 'amar_code' => '2108'],
            ['id' => 36, 'name' => 'اشنویه', 'province_id' => 2, 'amar_code' => '413'],
            ['id' => 37, 'name' => 'اصفهان', 'province_id' => 4, 'amar_code' => '1002'],
            ['id' => 38, 'name' => 'اصلاندوز', 'province_id' => 3, 'amar_code' => '2411'],
            ['id' => 39, 'name' => 'اقلید', 'province_id' => 17, 'amar_code' => '703'],
            ['id' => 40, 'name' => 'البرز', 'province_id' => 18, 'amar_code' => '2605'],
            ['id' => 41, 'name' => 'الیگودرز', 'province_id' => 26, 'amar_code' => '1501'],
            ['id' => 42, 'name' => 'املش', 'province_id' => 25, 'amar_code' => '113'],
            ['id' => 43, 'name' => 'امیدیه', 'province_id' => 13, 'amar_code' => '616'],
            ['id' => 44, 'name' => 'انار', 'province_id' => 21, 'amar_code' => '820'],
            ['id' => 45, 'name' => 'اندیکا', 'province_id' => 13, 'amar_code' => '621'],
            ['id' => 46, 'name' => 'اندیمشک', 'province_id' => 13, 'amar_code' => '602'],
            ['id' => 47, 'name' => 'اوز', 'province_id' => 17, 'amar_code' => '736'],
            ['id' => 48, 'name' => 'اهر', 'province_id' => 1, 'amar_code' => '302'],
            ['id' => 49, 'name' => 'اهواز', 'province_id' => 13, 'amar_code' => '603'],
            ['id' => 50, 'name' => 'ایجرود', 'province_id' => 14, 'amar_code' => '1906'],
            ['id' => 51, 'name' => 'ایذه', 'province_id' => 13, 'amar_code' => '604'],
            ['id' => 52, 'name' => 'ایرانشهر', 'province_id' => 16, 'amar_code' => '1101'],
            ['id' => 53, 'name' => 'ایلام', 'province_id' => 6, 'amar_code' => '1601'],
            ['id' => 54, 'name' => 'ایوان', 'province_id' => 6, 'amar_code' => '1607'],
            ['id' => 55, 'name' => 'بابل', 'province_id' => 27, 'amar_code' => '202'],
            ['id' => 56, 'name' => 'بابلسر', 'province_id' => 27, 'amar_code' => '216'],
            ['id' => 57, 'name' => 'باخرز', 'province_id' => 11, 'amar_code' => '937'],
            ['id' => 58, 'name' => 'باشت', 'province_id' => 23, 'amar_code' => '1707'],
            ['id' => 59, 'name' => 'باغ ملک', 'province_id' => 13, 'amar_code' => '615'],
            ['id' => 60, 'name' => 'بافت', 'province_id' => 21, 'amar_code' => '801'],
            ['id' => 61, 'name' => 'بافق', 'province_id' => 31, 'amar_code' => '2102'],
            ['id' => 62, 'name' => 'بانه', 'province_id' => 20, 'amar_code' => '1201'],
            ['id' => 63, 'name' => 'باوی', 'province_id' => 13, 'amar_code' => '624'],
            ['id' => 64, 'name' => 'بجستان', 'province_id' => 11, 'amar_code' => '931'],
            ['id' => 65, 'name' => 'بجنورد', 'province_id' => 12, 'amar_code' => '2802'],
            ['id' => 66, 'name' => 'بختگان', 'province_id' => 17, 'amar_code' => '735'],
            ['id' => 67, 'name' => 'بدره', 'province_id' => 6, 'amar_code' => '1610'],
            ['id' => 68, 'name' => 'برخوار', 'province_id' => 4, 'amar_code' => '1022'],
            ['id' => 69, 'name' => 'بردسکن', 'province_id' => 11, 'amar_code' => '923'],
            ['id' => 70, 'name' => 'بردسیر', 'province_id' => 21, 'amar_code' => '810'],
            ['id' => 71, 'name' => 'بروجرد', 'province_id' => 26, 'amar_code' => '1502'],
            ['id' => 72, 'name' => 'بروجن', 'province_id' => 9, 'amar_code' => '1401'],
            ['id' => 73, 'name' => 'بستان آباد', 'province_id' => 1, 'amar_code' => '313'],
            ['id' => 74, 'name' => 'بستک', 'province_id' => 29, 'amar_code' => '2209'],
            ['id' => 75, 'name' => 'بشاگرد', 'province_id' => 29, 'amar_code' => '2213'],
            ['id' => 76, 'name' => 'بشرویه', 'province_id' => 10, 'amar_code' => '2908'],
            ['id' => 77, 'name' => 'بم', 'province_id' => 21, 'amar_code' => '802'],
            ['id' => 78, 'name' => 'بمپور', 'province_id' => 16, 'amar_code' => '1120'],
            ['id' => 79, 'name' => 'بن', 'province_id' => 9, 'amar_code' => '1409'],
            ['id' => 80, 'name' => 'بناب', 'province_id' => 1, 'amar_code' => '312'],
            ['id' => 81, 'name' => 'بندرانزلی', 'province_id' => 25, 'amar_code' => '103'],
            ['id' => 82, 'name' => 'بندرعباس', 'province_id' => 29, 'amar_code' => '2202'],
            ['id' => 83, 'name' => 'بندرگز', 'province_id' => 24, 'amar_code' => '2701'],
            ['id' => 84, 'name' => 'بندرلنگه', 'province_id' => 29, 'amar_code' => '2203'],
            ['id' => 85, 'name' => 'بندرماهشهر', 'province_id' => 13, 'amar_code' => '605'],
            ['id' => 86, 'name' => 'بویین و میاندشت', 'province_id' => 4, 'amar_code' => '1024'],
            ['id' => 87, 'name' => 'بوانات', 'province_id' => 17, 'amar_code' => '716'],
            ['id' => 88, 'name' => 'بوشهر', 'province_id' => 7, 'amar_code' => '1801'],
            ['id' => 89, 'name' => 'بوکان', 'province_id' => 2, 'amar_code' => '410'],
            ['id' => 90, 'name' => 'بویراحمد', 'province_id' => 23, 'amar_code' => '1701'],
            ['id' => 91, 'name' => 'بویین زهرا', 'province_id' => 18, 'amar_code' => '2601'],
            ['id' => 92, 'name' => 'بهاباد', 'province_id' => 31, 'amar_code' => '2111'],
            ['id' => 93, 'name' => 'بهار', 'province_id' => 30, 'amar_code' => '1307'],
            ['id' => 94, 'name' => 'بهارستان', 'province_id' => 8, 'amar_code' => '2319'],
            ['id' => 95, 'name' => 'بهبهان', 'province_id' => 13, 'amar_code' => '606'],
            ['id' => 96, 'name' => 'بهشهر', 'province_id' => 27, 'amar_code' => '204'],
            ['id' => 97, 'name' => 'بهمیی', 'province_id' => 23, 'amar_code' => '1705'],
            ['id' => 98, 'name' => 'بیجار', 'province_id' => 20, 'amar_code' => '1202'],
            ['id' => 99, 'name' => 'بیرجند', 'province_id' => 10, 'amar_code' => '2901'],
            ['id' => 100, 'name' => 'بیضا', 'province_id' => 17, 'amar_code' => '731'],
            ['id' => 101, 'name' => 'بیله سوار', 'province_id' => 3, 'amar_code' => '2402'],
            ['id' => 102, 'name' => 'بینالود', 'province_id' => 11, 'amar_code' => '932'],
            ['id' => 103, 'name' => 'پارس آباد', 'province_id' => 3, 'amar_code' => '2406'],
            ['id' => 104, 'name' => 'پارسیان', 'province_id' => 29, 'amar_code' => '2211'],
            ['id' => 105, 'name' => 'پاسارگاد', 'province_id' => 17, 'amar_code' => '723'],
            ['id' => 106, 'name' => 'پاکدشت', 'province_id' => 8, 'amar_code' => '2313'],
            ['id' => 107, 'name' => 'پاوه', 'province_id' => 22, 'amar_code' => '503'],
            ['id' => 108, 'name' => 'پردیس', 'province_id' => 8, 'amar_code' => '2320'],
            ['id' => 109, 'name' => 'پلدختر', 'province_id' => 26, 'amar_code' => '1508'],
            ['id' => 110, 'name' => 'پلدشت', 'province_id' => 2, 'amar_code' => '415'],
            ['id' => 111, 'name' => 'پیرانشهر', 'province_id' => 2, 'amar_code' => '402'],
            ['id' => 112, 'name' => 'پیشوا', 'province_id' => 8, 'amar_code' => '2318'],
            ['id' => 113, 'name' => 'تاکستان', 'province_id' => 18, 'amar_code' => '2602'],
            ['id' => 114, 'name' => 'تایباد', 'province_id' => 11, 'amar_code' => '904'],
            ['id' => 115, 'name' => 'تبریز', 'province_id' => 1, 'amar_code' => '303'],
            ['id' => 116, 'name' => 'تربت جام', 'province_id' => 11, 'amar_code' => '906'],
            ['id' => 117, 'name' => 'تربت حیدریه', 'province_id' => 11, 'amar_code' => '905'],
            ['id' => 118, 'name' => 'ترکمن', 'province_id' => 24, 'amar_code' => '2702'],
            ['id' => 119, 'name' => 'تفت', 'province_id' => 31, 'amar_code' => '2103'],
            ['id' => 120, 'name' => 'تفتان', 'province_id' => 16, 'amar_code' => '1121'],
            ['id' => 121, 'name' => 'تفرش', 'province_id' => 28, 'amar_code' => '3'],
            ['id' => 122, 'name' => 'تکاب', 'province_id' => 2, 'amar_code' => '412'],
            ['id' => 123, 'name' => 'تنکابن', 'province_id' => 27, 'amar_code' => '205'],
            ['id' => 124, 'name' => 'تنگستان', 'province_id' => 7, 'amar_code' => '1802'],
            ['id' => 125, 'name' => 'تویسرکان', 'province_id' => 30, 'amar_code' => '1301'],
            ['id' => 126, 'name' => 'تهران', 'province_id' => 8, 'amar_code' => '2301'],
            ['id' => 127, 'name' => 'تیران و کرون', 'province_id' => 4, 'amar_code' => '1019'],
            ['id' => 128, 'name' => 'ثلاث باباجانی', 'province_id' => 22, 'amar_code' => '512'],
            ['id' => 129, 'name' => 'جاجرم', 'province_id' => 12, 'amar_code' => '2803'],
            ['id' => 130, 'name' => 'جاسک', 'province_id' => 29, 'amar_code' => '2206'],
            ['id' => 131, 'name' => 'جغتای', 'province_id' => 11, 'amar_code' => '934'],
            ['id' => 132, 'name' => 'جلفا', 'province_id' => 1, 'amar_code' => '319'],
            ['id' => 133, 'name' => 'جم', 'province_id' => 7, 'amar_code' => '1809'],
            ['id' => 134, 'name' => 'جوانرود', 'province_id' => 22, 'amar_code' => '509'],
            ['id' => 135, 'name' => 'جویبار', 'province_id' => 27, 'amar_code' => '221'],
            ['id' => 136, 'name' => 'جوین', 'province_id' => 11, 'amar_code' => '936'],
            ['id' => 137, 'name' => 'جهرم', 'province_id' => 17, 'amar_code' => '704'],
            ['id' => 138, 'name' => 'جیرفت', 'province_id' => 21, 'amar_code' => '803'],
            ['id' => 139, 'name' => 'چادگان', 'province_id' => 4, 'amar_code' => '1020'],
            ['id' => 140, 'name' => 'چاراویماق', 'province_id' => 1, 'amar_code' => '323'],
            ['id' => 141, 'name' => 'چالدران', 'province_id' => 2, 'amar_code' => '414'],
            ['id' => 142, 'name' => 'چالوس', 'province_id' => 27, 'amar_code' => '220'],
            ['id' => 143, 'name' => 'چابهار', 'province_id' => 16, 'amar_code' => '1102'],
            ['id' => 144, 'name' => 'چایپاره', 'province_id' => 2, 'amar_code' => '416'],
            ['id' => 145, 'name' => 'چرام', 'province_id' => 23, 'amar_code' => '1706'],
            ['id' => 146, 'name' => 'چرداول', 'province_id' => 6, 'amar_code' => '1604'],
            ['id' => 147, 'name' => 'چگنی', 'province_id' => 26, 'amar_code' => '1510'],
            ['id' => 148, 'name' => 'چناران', 'province_id' => 11, 'amar_code' => '918'],
            ['id' => 149, 'name' => 'حاجی‌آباد', 'province_id' => 29, 'amar_code' => '2208'],
            ['id' => 150, 'name' => 'حمیدیه', 'province_id' => 13, 'amar_code' => '625'],
            ['id' => 151, 'name' => 'خاتم', 'province_id' => 31, 'amar_code' => '2109'],
            ['id' => 152, 'name' => 'خاش', 'province_id' => 16, 'amar_code' => '1103'],
            ['id' => 153, 'name' => 'خانمیرزا', 'province_id' => 9, 'amar_code' => '1410'],
            ['id' => 154, 'name' => 'خداآفرین', 'province_id' => 1, 'amar_code' => '326'],
            ['id' => 155, 'name' => 'خدابنده', 'province_id' => 14, 'amar_code' => '1903'],
            ['id' => 156, 'name' => 'خرامه', 'province_id' => 17, 'amar_code' => '729'],
            ['id' => 157, 'name' => 'خرم آباد', 'province_id' => 26, 'amar_code' => '1503'],
            ['id' => 158, 'name' => 'خرم بید', 'province_id' => 17, 'amar_code' => '718'],
            ['id' => 159, 'name' => 'خرمدره', 'province_id' => 14, 'amar_code' => '1907'],
            ['id' => 160, 'name' => 'خرمشهر', 'province_id' => 13, 'amar_code' => '607'],
            ['id' => 161, 'name' => 'خفر', 'province_id' => 17, 'amar_code' => '734'],
            ['id' => 162, 'name' => 'خلخال', 'province_id' => 3, 'amar_code' => '2403'],
            ['id' => 163, 'name' => 'خلیل آباد', 'province_id' => 11, 'amar_code' => '929'],
            ['id' => 164, 'name' => 'خمیر', 'province_id' => 29, 'amar_code' => '2210'],
            ['id' => 165, 'name' => 'خمین', 'province_id' => 28, 'amar_code' => '4'],
            ['id' => 166, 'name' => 'خمینی شهر', 'province_id' => 4, 'amar_code' => '1003'],
            ['id' => 167, 'name' => 'خنج', 'province_id' => 17, 'amar_code' => '724'],
            ['id' => 168, 'name' => 'خنداب', 'province_id' => 28, 'amar_code' => '12'],
            ['id' => 169, 'name' => 'خواف', 'province_id' => 11, 'amar_code' => '919'],
            ['id' => 170, 'name' => 'خوانسار', 'province_id' => 4, 'amar_code' => '1004'],
            ['id' => 171, 'name' => 'خور و بیابانک', 'province_id' => 4, 'amar_code' => '1023'],
            ['id' => 172, 'name' => 'خوسف', 'province_id' => 10, 'amar_code' => '2910'],
            ['id' => 173, 'name' => 'خوشاب', 'province_id' => 11, 'amar_code' => '938'],
            ['id' => 174, 'name' => 'خوی', 'province_id' => 2, 'amar_code' => '403'],
            ['id' => 175, 'name' => 'داراب', 'province_id' => 17, 'amar_code' => '705'],
            ['id' => 176, 'name' => 'دالاهو', 'province_id' => 22, 'amar_code' => '513'],
            ['id' => 177, 'name' => 'دامغان', 'province_id' => 15, 'amar_code' => '2001'],
            ['id' => 178, 'name' => 'داورزن', 'province_id' => 11, 'amar_code' => '939'],
            ['id' => 179, 'name' => 'درگز', 'province_id' => 11, 'amar_code' => '907'],
            ['id' => 180, 'name' => 'درگزین', 'province_id' => 30, 'amar_code' => '1310'],
            ['id' => 181, 'name' => 'درمیان', 'province_id' => 10, 'amar_code' => '2902'],
            ['id' => 182, 'name' => 'دره شهر', 'province_id' => 6, 'amar_code' => '1602'],
            ['id' => 183, 'name' => 'دزفول', 'province_id' => 13, 'amar_code' => '608'],
            ['id' => 184, 'name' => 'دشت آزادگان', 'province_id' => 13, 'amar_code' => '609'],
            ['id' => 185, 'name' => 'دشتستان', 'province_id' => 7, 'amar_code' => '1803'],
            ['id' => 186, 'name' => 'دشتی', 'province_id' => 7, 'amar_code' => '1804'],
            ['id' => 187, 'name' => 'دشتیاری', 'province_id' => 16, 'amar_code' => '1122'],
            ['id' => 188, 'name' => 'دلفان', 'province_id' => 26, 'amar_code' => '1504'],
            ['id' => 189, 'name' => 'دلگان', 'province_id' => 16, 'amar_code' => '1112'],
            ['id' => 190, 'name' => 'دلیجان', 'province_id' => 28, 'amar_code' => '5'],
            ['id' => 191, 'name' => 'دماوند', 'province_id' => 8, 'amar_code' => '2302'],
            ['id' => 192, 'name' => 'دنا', 'province_id' => 23, 'amar_code' => '1704'],
            ['id' => 193, 'name' => 'دورود', 'province_id' => 26, 'amar_code' => '1505'],
            ['id' => 194, 'name' => 'دهاقان', 'province_id' => 4, 'amar_code' => '1021'],
            ['id' => 195, 'name' => 'دهگلان', 'province_id' => 20, 'amar_code' => '1210'],
            ['id' => 196, 'name' => 'دهلران', 'province_id' => 6, 'amar_code' => '1603'],
            ['id' => 197, 'name' => 'دیر', 'province_id' => 7, 'amar_code' => '1805'],
            ['id' => 198, 'name' => 'دیلم', 'province_id' => 7, 'amar_code' => '1808'],
            ['id' => 199, 'name' => 'دیواندره', 'province_id' => 20, 'amar_code' => '1207'],
            ['id' => 200, 'name' => 'رابر', 'province_id' => 21, 'amar_code' => '818'],
            ['id' => 201, 'name' => 'راز و جرگلان', 'province_id' => 12, 'amar_code' => '2808'],
            ['id' => 202, 'name' => 'راسک', 'province_id' => 16, 'amar_code' => '1108'],
            ['id' => 203, 'name' => 'رامسر', 'province_id' => 27, 'amar_code' => '206'],
            ['id' => 204, 'name' => 'رامشیر', 'province_id' => 13, 'amar_code' => '619'],
            ['id' => 205, 'name' => 'رامهرمز', 'province_id' => 13, 'amar_code' => '610'],
            ['id' => 206, 'name' => 'رامیان', 'province_id' => 24, 'amar_code' => '2711'],
            ['id' => 207, 'name' => 'راور', 'province_id' => 21, 'amar_code' => '811'],
            ['id' => 208, 'name' => 'رباط کریم', 'province_id' => 8, 'amar_code' => '2312'],
            ['id' => 209, 'name' => 'رزن', 'province_id' => 30, 'amar_code' => '1308'],
            ['id' => 210, 'name' => 'رستم', 'province_id' => 17, 'amar_code' => '726'],
            ['id' => 211, 'name' => 'رشت', 'province_id' => 25, 'amar_code' => '105'],
            ['id' => 212, 'name' => 'رشتخوار', 'province_id' => 11, 'amar_code' => '927'],
            ['id' => 213, 'name' => 'رضوانشهر', 'province_id' => 25, 'amar_code' => '114'],
            ['id' => 214, 'name' => 'رفسنجان', 'province_id' => 21, 'amar_code' => '804'],
            ['id' => 215, 'name' => 'روانسر', 'province_id' => 22, 'amar_code' => '514'],
            ['id' => 216, 'name' => 'رودان', 'province_id' => 29, 'amar_code' => '2207'],
            ['id' => 217, 'name' => 'رودبار', 'province_id' => 25, 'amar_code' => '106'],
            ['id' => 218, 'name' => 'رودبارجنوب', 'province_id' => 21, 'amar_code' => '815'],
            ['id' => 219, 'name' => 'رودسر', 'province_id' => 25, 'amar_code' => '107'],
            ['id' => 220, 'name' => 'رومشکان', 'province_id' => 26, 'amar_code' => '1511'],
            ['id' => 221, 'name' => 'ری', 'province_id' => 8, 'amar_code' => '2303'],
            ['id' => 222, 'name' => 'ریگان', 'province_id' => 21, 'amar_code' => '817'],
            ['id' => 223, 'name' => 'زابل', 'province_id' => 16, 'amar_code' => '1104'],
            ['id' => 224, 'name' => 'زاوه', 'province_id' => 11, 'amar_code' => '935'],
            ['id' => 225, 'name' => 'زاهدان', 'province_id' => 16, 'amar_code' => '1105'],
            ['id' => 226, 'name' => 'زرقان', 'province_id' => 17, 'amar_code' => '730'],
            ['id' => 227, 'name' => 'زرند', 'province_id' => 21, 'amar_code' => '805'],
            ['id' => 228, 'name' => 'زرندیه', 'province_id' => 28, 'amar_code' => '10'],
            ['id' => 229, 'name' => 'زرین دشت', 'province_id' => 17, 'amar_code' => '719'],
            ['id' => 230, 'name' => 'زنجان', 'province_id' => 14, 'amar_code' => '1904'],
            ['id' => 231, 'name' => 'زهک', 'province_id' => 16, 'amar_code' => '1110'],
            ['id' => 232, 'name' => 'زیرکوه', 'province_id' => 10, 'amar_code' => '2909'],
            ['id' => 233, 'name' => 'ساری', 'province_id' => 27, 'amar_code' => '207'],
            ['id' => 234, 'name' => 'سامان', 'province_id' => 9, 'amar_code' => '1408'],
            ['id' => 235, 'name' => 'ساوجبلاغ', 'province_id' => 5, 'amar_code' => '3002'],
            ['id' => 236, 'name' => 'ساوه', 'province_id' => 28, 'amar_code' => '6'],
            ['id' => 237, 'name' => 'سبزوار', 'province_id' => 11, 'amar_code' => '908'],
            ['id' => 238, 'name' => 'سپیدان', 'province_id' => 17, 'amar_code' => '706'],
            ['id' => 239, 'name' => 'سراب', 'province_id' => 1, 'amar_code' => '305'],
            ['id' => 240, 'name' => 'سراوان', 'province_id' => 16, 'amar_code' => '1106'],
            ['id' => 241, 'name' => 'سرایان', 'province_id' => 10, 'amar_code' => '2906'],
            ['id' => 242, 'name' => 'سرباز', 'province_id' => 16, 'amar_code' => '1123'],
            ['id' => 243, 'name' => 'سربیشه', 'province_id' => 10, 'amar_code' => '2903'],
            ['id' => 244, 'name' => 'سرپل ذهاب', 'province_id' => 22, 'amar_code' => '504'],
            ['id' => 245, 'name' => 'سرچهان', 'province_id' => 17, 'amar_code' => '732'],
            ['id' => 246, 'name' => 'سرخس', 'province_id' => 11, 'amar_code' => '920'],
            ['id' => 247, 'name' => 'سرخه', 'province_id' => 15, 'amar_code' => '2008'],
            ['id' => 248, 'name' => 'سردشت', 'province_id' => 2, 'amar_code' => '404'],
            ['id' => 249, 'name' => 'سرعین', 'province_id' => 3, 'amar_code' => '2410'],
            ['id' => 250, 'name' => 'سروآباد', 'province_id' => 20, 'amar_code' => '1209'],
            ['id' => 251, 'name' => 'سروستان', 'province_id' => 17, 'amar_code' => '725'],
            ['id' => 252, 'name' => 'سقز', 'province_id' => 20, 'amar_code' => '1203'],
            ['id' => 253, 'name' => 'سلسله', 'province_id' => 26, 'amar_code' => '1509'],
            ['id' => 254, 'name' => 'سلطانیه', 'province_id' => 14, 'amar_code' => '1910'],
            ['id' => 255, 'name' => 'سلماس', 'province_id' => 2, 'amar_code' => '405'],
            ['id' => 256, 'name' => 'سمنان', 'province_id' => 15, 'amar_code' => '2002'],
            ['id' => 257, 'name' => 'سمیرم', 'province_id' => 4, 'amar_code' => '1005'],
            ['id' => 258, 'name' => 'سنقر', 'province_id' => 22, 'amar_code' => '505'],
            ['id' => 259, 'name' => 'سنندج', 'province_id' => 20, 'amar_code' => '1204'],
            ['id' => 260, 'name' => 'سوادکوه', 'province_id' => 27, 'amar_code' => '208'],
            ['id' => 261, 'name' => 'سوادکوه شمالی', 'province_id' => 27, 'amar_code' => '227'],
            ['id' => 262, 'name' => 'سیاهکل', 'province_id' => 25, 'amar_code' => '115'],
            ['id' => 263, 'name' => 'سیب و سوران', 'province_id' => 16, 'amar_code' => '1114'],
            ['id' => 264, 'name' => 'سیرجان', 'province_id' => 21, 'amar_code' => '806'],
            ['id' => 265, 'name' => 'سیروان', 'province_id' => 6, 'amar_code' => '1609'],
            ['id' => 266, 'name' => 'سیریک', 'province_id' => 29, 'amar_code' => '2212'],
            ['id' => 267, 'name' => 'سیمرغ', 'province_id' => 27, 'amar_code' => '226'],
            ['id' => 268, 'name' => 'شادگان', 'province_id' => 13, 'amar_code' => '611'],
            ['id' => 269, 'name' => 'شازند', 'province_id' => 28, 'amar_code' => '7'],
            ['id' => 270, 'name' => 'شاهرود', 'province_id' => 15, 'amar_code' => '2003'],
            ['id' => 271, 'name' => 'شاهین دژ', 'province_id' => 2, 'amar_code' => '411'],
            ['id' => 272, 'name' => 'شاهین‌شهر و میمه', 'province_id' => 4, 'amar_code' => '1016'],
            ['id' => 273, 'name' => 'شبستر', 'province_id' => 1, 'amar_code' => '314'],
            ['id' => 274, 'name' => 'شفت', 'province_id' => 25, 'amar_code' => '112'],
            ['id' => 275, 'name' => 'شمیرانات', 'province_id' => 8, 'amar_code' => '2304'],
            ['id' => 276, 'name' => 'شوش', 'province_id' => 13, 'amar_code' => '614'],
            ['id' => 277, 'name' => 'شوشتر', 'province_id' => 13, 'amar_code' => '612'],
            ['id' => 278, 'name' => 'شوط', 'province_id' => 2, 'amar_code' => '417'],
            ['id' => 279, 'name' => 'شهربابک', 'province_id' => 21, 'amar_code' => '807'],
            ['id' => 280, 'name' => 'شهرضا', 'province_id' => 4, 'amar_code' => '1009'],
            ['id' => 281, 'name' => 'شهرکرد', 'province_id' => 9, 'amar_code' => '1402'],
            ['id' => 282, 'name' => 'شهریار', 'province_id' => 8, 'amar_code' => '2309'],
            ['id' => 283, 'name' => 'شیراز', 'province_id' => 17, 'amar_code' => '707'],
            ['id' => 284, 'name' => 'شیروان', 'province_id' => 12, 'amar_code' => '2804'],
            ['id' => 285, 'name' => 'صالح آباد', 'province_id' => 11, 'amar_code' => '940'],
            ['id' => 286, 'name' => 'صحنه', 'province_id' => 22, 'amar_code' => '510'],
            ['id' => 287, 'name' => 'صومعه سرا', 'province_id' => 25, 'amar_code' => '108'],
            ['id' => 288, 'name' => 'طارم', 'province_id' => 14, 'amar_code' => '1908'],
            ['id' => 289, 'name' => 'طالقان', 'province_id' => 5, 'amar_code' => '3004'],
            ['id' => 290, 'name' => 'طبس', 'province_id' => 10, 'amar_code' => '2911'],
            ['id' => 291, 'name' => 'طوالش', 'province_id' => 25, 'amar_code' => '104'],
            ['id' => 292, 'name' => 'عباس آباد', 'province_id' => 27, 'amar_code' => '224'],
            ['id' => 293, 'name' => 'عجب شیر', 'province_id' => 1, 'amar_code' => '325'],
            ['id' => 294, 'name' => 'عسلویه', 'province_id' => 7, 'amar_code' => '1810'],
            ['id' => 295, 'name' => 'علی آباد کتول', 'province_id' => 24, 'amar_code' => '2703'],
            ['id' => 296, 'name' => 'عنبرآباد', 'province_id' => 21, 'amar_code' => '812'],
            ['id' => 297, 'name' => 'فارسان', 'province_id' => 9, 'amar_code' => '1403'],
            ['id' => 298, 'name' => 'فاروج', 'province_id' => 12, 'amar_code' => '2805'],
            ['id' => 299, 'name' => 'فاریاب', 'province_id' => 21, 'amar_code' => '822'],
            ['id' => 300, 'name' => 'فامنین', 'province_id' => 30, 'amar_code' => '1309'],
            ['id' => 301, 'name' => 'فراشبند', 'province_id' => 17, 'amar_code' => '722'],
            ['id' => 302, 'name' => 'فراهان', 'province_id' => 28, 'amar_code' => '13'],
            ['id' => 303, 'name' => 'فردوس', 'province_id' => 10, 'amar_code' => '2907'],
            ['id' => 304, 'name' => 'فردیس', 'province_id' => 5, 'amar_code' => '3006'],
            ['id' => 305, 'name' => 'فریدن', 'province_id' => 4, 'amar_code' => '1006'],
            ['id' => 306, 'name' => 'فریدونشهر', 'province_id' => 4, 'amar_code' => '1007'],
            ['id' => 307, 'name' => 'فریدونکنار', 'province_id' => 27, 'amar_code' => '223'],
            ['id' => 308, 'name' => 'فریمان', 'province_id' => 11, 'amar_code' => '922'],
            ['id' => 309, 'name' => 'فسا', 'province_id' => 17, 'amar_code' => '708'],
            ['id' => 310, 'name' => 'فلاورجان', 'province_id' => 4, 'amar_code' => '1008'],
            ['id' => 311, 'name' => 'فنوج', 'province_id' => 16, 'amar_code' => '1119'],
            ['id' => 312, 'name' => 'فومن', 'province_id' => 25, 'amar_code' => '109'],
            ['id' => 313, 'name' => 'فهرج', 'province_id' => 21, 'amar_code' => '819'],
            ['id' => 314, 'name' => 'فیروزآباد', 'province_id' => 17, 'amar_code' => '709'],
            ['id' => 315, 'name' => 'فیروزکوه', 'province_id' => 8, 'amar_code' => '2314'],
            ['id' => 316, 'name' => 'فیروزه', 'province_id' => 11, 'amar_code' => '933'],
            ['id' => 317, 'name' => 'قایم شهر', 'province_id' => 27, 'amar_code' => '210'],
            ['id' => 318, 'name' => 'قاینات', 'province_id' => 10, 'amar_code' => '2904'],
            ['id' => 319, 'name' => 'قدس', 'province_id' => 8, 'amar_code' => '2316'],
            ['id' => 320, 'name' => 'قرچک', 'province_id' => 8, 'amar_code' => '2321'],
            ['id' => 321, 'name' => 'قروه', 'province_id' => 20, 'amar_code' => '1205'],
            ['id' => 322, 'name' => 'قزوین', 'province_id' => 18, 'amar_code' => '2603'],
            ['id' => 323, 'name' => 'قشم', 'province_id' => 29, 'amar_code' => '2204'],
            ['id' => 324, 'name' => 'قصرشیرین', 'province_id' => 22, 'amar_code' => '506'],
            ['id' => 325, 'name' => 'قصرقند', 'province_id' => 16, 'amar_code' => '1118'],
            ['id' => 326, 'name' => 'قلعه گنج', 'province_id' => 21, 'amar_code' => '816'],
            ['id' => 327, 'name' => 'قم', 'province_id' => 19, 'amar_code' => '2501'],
            ['id' => 328, 'name' => 'قوچان', 'province_id' => 11, 'amar_code' => '913'],
            ['id' => 329, 'name' => 'قیر و کارزین', 'province_id' => 17, 'amar_code' => '720'],
            ['id' => 330, 'name' => 'کارون', 'province_id' => 13, 'amar_code' => '627'],
            ['id' => 331, 'name' => 'کازرون', 'province_id' => 17, 'amar_code' => '710'],
            ['id' => 332, 'name' => 'کاشان', 'province_id' => 4, 'amar_code' => '1010'],
            ['id' => 333, 'name' => 'کاشمر', 'province_id' => 11, 'amar_code' => '914'],
            ['id' => 334, 'name' => 'کامیاران', 'province_id' => 20, 'amar_code' => '1208'],
            ['id' => 335, 'name' => 'کبودرآهنگ', 'province_id' => 30, 'amar_code' => '1305'],
            ['id' => 336, 'name' => 'کرج', 'province_id' => 5, 'amar_code' => '3001'],
            ['id' => 337, 'name' => 'کردکوی', 'province_id' => 24, 'amar_code' => '2704'],
            ['id' => 338, 'name' => 'کرمان', 'province_id' => 21, 'amar_code' => '808'],
            ['id' => 339, 'name' => 'کرمانشاه', 'province_id' => 22, 'amar_code' => '502'],
            ['id' => 340, 'name' => 'کلات', 'province_id' => 11, 'amar_code' => '928'],
            ['id' => 341, 'name' => 'کلاردشت', 'province_id' => 27, 'amar_code' => '228'],
            ['id' => 342, 'name' => 'کلاله', 'province_id' => 24, 'amar_code' => '2709'],
            ['id' => 343, 'name' => 'کلیبر', 'province_id' => 1, 'amar_code' => '315'],
            ['id' => 344, 'name' => 'کمیجان', 'province_id' => 28, 'amar_code' => '11'],
            ['id' => 345, 'name' => 'کنارک', 'province_id' => 16, 'amar_code' => '1109'],
            ['id' => 346, 'name' => 'کنگان', 'province_id' => 7, 'amar_code' => '1806'],
            ['id' => 347, 'name' => 'کنگاور', 'province_id' => 22, 'amar_code' => '507'],
            ['id' => 348, 'name' => 'کوار', 'province_id' => 17, 'amar_code' => '728'],
            ['id' => 349, 'name' => 'کوثر', 'province_id' => 3, 'amar_code' => '2407'],
            ['id' => 350, 'name' => 'کوه چنار', 'province_id' => 17, 'amar_code' => '733'],
            ['id' => 351, 'name' => 'کوهبنان', 'province_id' => 21, 'amar_code' => '814'],
            ['id' => 352, 'name' => 'کوهدشت', 'province_id' => 26, 'amar_code' => '1506'],
            ['id' => 353, 'name' => 'کوهرنگ', 'province_id' => 9, 'amar_code' => '1406'],
            ['id' => 354, 'name' => 'کوهسرخ', 'province_id' => 11, 'amar_code' => '941'],
            ['id' => 355, 'name' => 'کهگیلویه', 'province_id' => 23, 'amar_code' => '1702'],
            ['id' => 356, 'name' => 'کهنوج', 'province_id' => 21, 'amar_code' => '809'],
            ['id' => 357, 'name' => 'کیار', 'province_id' => 9, 'amar_code' => '1407'],
            ['id' => 358, 'name' => 'گالیکش', 'province_id' => 24, 'amar_code' => '2714'],
            ['id' => 359, 'name' => 'گتوند', 'province_id' => 13, 'amar_code' => '620'],
            ['id' => 360, 'name' => 'گچساران', 'province_id' => 23, 'amar_code' => '1703'],
            ['id' => 361, 'name' => 'گراش', 'province_id' => 17, 'amar_code' => '727'],
            ['id' => 362, 'name' => 'گرگان', 'province_id' => 24, 'amar_code' => '2705'],
            ['id' => 363, 'name' => 'گرمسار', 'province_id' => 15, 'amar_code' => '2004'],
            ['id' => 364, 'name' => 'گرمه', 'province_id' => 12, 'amar_code' => '2807'],
            ['id' => 365, 'name' => 'گرمی', 'province_id' => 3, 'amar_code' => '2405'],
            ['id' => 366, 'name' => 'گلپایگان', 'province_id' => 4, 'amar_code' => '1011'],
            ['id' => 367, 'name' => 'گلوگاه', 'province_id' => 27, 'amar_code' => '222'],
            ['id' => 368, 'name' => 'گمیشان', 'province_id' => 24, 'amar_code' => '2713'],
            ['id' => 369, 'name' => 'گناباد', 'province_id' => 11, 'amar_code' => '915'],
            ['id' => 370, 'name' => 'گناوه', 'province_id' => 7, 'amar_code' => '1807'],
            ['id' => 371, 'name' => 'گنبدکاووس', 'province_id' => 24, 'amar_code' => '2706'],
            ['id' => 372, 'name' => 'گیلانغرب', 'province_id' => 22, 'amar_code' => '508'],
            ['id' => 373, 'name' => 'لارستان', 'province_id' => 17, 'amar_code' => '711'],
            ['id' => 374, 'name' => 'لالی', 'province_id' => 13, 'amar_code' => '617'],
            ['id' => 375, 'name' => 'لامرد', 'province_id' => 17, 'amar_code' => '715'],
            ['id' => 376, 'name' => 'لاهیجان', 'province_id' => 25, 'amar_code' => '111'],
            ['id' => 377, 'name' => 'لردگان', 'province_id' => 9, 'amar_code' => '1404'],
            ['id' => 378, 'name' => 'لنجان', 'province_id' => 4, 'amar_code' => '1012'],
            ['id' => 379, 'name' => 'لنده', 'province_id' => 23, 'amar_code' => '1708'],
            ['id' => 380, 'name' => 'لنگرود', 'province_id' => 25, 'amar_code' => '110'],
            ['id' => 381, 'name' => 'مارگون', 'province_id' => 23, 'amar_code' => '1709'],
            ['id' => 382, 'name' => 'ماسال', 'province_id' => 25, 'amar_code' => '116'],
            ['id' => 383, 'name' => 'ماکو', 'province_id' => 2, 'amar_code' => '406'],
            ['id' => 384, 'name' => 'مانه وسملقان', 'province_id' => 12, 'amar_code' => '2806'],
            ['id' => 385, 'name' => 'ماهنشان', 'province_id' => 14, 'amar_code' => '1909'],
            ['id' => 386, 'name' => 'مبارکه', 'province_id' => 4, 'amar_code' => '1017'],
            ['id' => 387, 'name' => 'محلات', 'province_id' => 28, 'amar_code' => '9'],
            ['id' => 388, 'name' => 'محمودآباد', 'province_id' => 27, 'amar_code' => '218'],
            ['id' => 389, 'name' => 'مراغه', 'province_id' => 1, 'amar_code' => '306'],
            ['id' => 390, 'name' => 'مراوه تپه', 'province_id' => 24, 'amar_code' => '2712'],
            ['id' => 391, 'name' => 'مرند', 'province_id' => 1, 'amar_code' => '307'],
            ['id' => 392, 'name' => 'مرودشت', 'province_id' => 17, 'amar_code' => '712'],
            ['id' => 393, 'name' => 'مریوان', 'province_id' => 20, 'amar_code' => '1206'],
            ['id' => 394, 'name' => 'مسجدسلیمان', 'province_id' => 13, 'amar_code' => '613'],
            ['id' => 395, 'name' => 'مشگین شهر', 'province_id' => 3, 'amar_code' => '2404'],
            ['id' => 396, 'name' => 'مشهد', 'province_id' => 11, 'amar_code' => '916'],
            ['id' => 397, 'name' => 'ملارد', 'province_id' => 8, 'amar_code' => '2317'],
            ['id' => 398, 'name' => 'ملایر', 'province_id' => 30, 'amar_code' => '1302'],
            ['id' => 399, 'name' => 'ملکان', 'province_id' => 1, 'amar_code' => '320'],
            ['id' => 400, 'name' => 'ملکشاهی', 'province_id' => 6, 'amar_code' => '1608'],
            ['id' => 401, 'name' => 'ممسنی', 'province_id' => 17, 'amar_code' => '713'],
            ['id' => 402, 'name' => 'منوجان', 'province_id' => 21, 'amar_code' => '813'],
            ['id' => 403, 'name' => 'مه ولات', 'province_id' => 11, 'amar_code' => '930'],
            ['id' => 404, 'name' => 'مهاباد', 'province_id' => 2, 'amar_code' => '407'],
            ['id' => 405, 'name' => 'مهدی شهر', 'province_id' => 15, 'amar_code' => '2005'],
            ['id' => 406, 'name' => 'مهر', 'province_id' => 17, 'amar_code' => '721'],
            ['id' => 407, 'name' => 'مهران', 'province_id' => 6, 'amar_code' => '1605'],
            ['id' => 408, 'name' => 'مهرستان', 'province_id' => 16, 'amar_code' => '1113'],
            ['id' => 409, 'name' => 'مهریز', 'province_id' => 31, 'amar_code' => '2104'],
            ['id' => 410, 'name' => 'میامی', 'province_id' => 15, 'amar_code' => '2007'],
            ['id' => 411, 'name' => 'میاندوآب', 'province_id' => 2, 'amar_code' => '408'],
            ['id' => 412, 'name' => 'میاندورود', 'province_id' => 27, 'amar_code' => '225'],
            ['id' => 413, 'name' => 'میانه', 'province_id' => 1, 'amar_code' => '310'],
            ['id' => 414, 'name' => 'میبد', 'province_id' => 31, 'amar_code' => '2106'],
            ['id' => 415, 'name' => 'میرجاوه', 'province_id' => 16, 'amar_code' => '1117'],
            ['id' => 416, 'name' => 'میناب', 'province_id' => 29, 'amar_code' => '2205'],
            ['id' => 417, 'name' => 'مینودشت', 'province_id' => 24, 'amar_code' => '2707'],
            ['id' => 418, 'name' => 'نایین', 'province_id' => 4, 'amar_code' => '1013'],
            ['id' => 419, 'name' => 'نجف آباد', 'province_id' => 4, 'amar_code' => '1014'],
            ['id' => 420, 'name' => 'نرماشیر', 'province_id' => 21, 'amar_code' => '821'],
            ['id' => 421, 'name' => 'نطنز', 'province_id' => 4, 'amar_code' => '1015'],
            ['id' => 422, 'name' => 'نظرآباد', 'province_id' => 5, 'amar_code' => '3003'],
            ['id' => 423, 'name' => 'نقده', 'province_id' => 2, 'amar_code' => '409'],
            ['id' => 424, 'name' => 'نکا', 'province_id' => 27, 'amar_code' => '219'],
            ['id' => 425, 'name' => 'نمین', 'province_id' => 3, 'amar_code' => '2408'],
            ['id' => 426, 'name' => 'نور', 'province_id' => 27, 'amar_code' => '214'],
            ['id' => 427, 'name' => 'نوشهر', 'province_id' => 27, 'amar_code' => '215'],
            ['id' => 428, 'name' => 'نهاوند', 'province_id' => 30, 'amar_code' => '1303'],
            ['id' => 429, 'name' => 'نهبندان', 'province_id' => 10, 'amar_code' => '2905'],
            ['id' => 430, 'name' => 'نی ریز', 'province_id' => 17, 'amar_code' => '714'],
            ['id' => 431, 'name' => 'نیر', 'province_id' => 3, 'amar_code' => '2409'],
            ['id' => 432, 'name' => 'نیشابور', 'province_id' => 11, 'amar_code' => '917'],
            ['id' => 433, 'name' => 'نیک شهر', 'province_id' => 16, 'amar_code' => '1107'],
            ['id' => 434, 'name' => 'نیمروز', 'province_id' => 16, 'amar_code' => '1115'],
            ['id' => 435, 'name' => 'ورامین', 'province_id' => 8, 'amar_code' => '2306'],
            ['id' => 436, 'name' => 'ورزقان', 'province_id' => 1, 'amar_code' => '324'],
            ['id' => 437, 'name' => 'هامون', 'province_id' => 16, 'amar_code' => '1116'],
            ['id' => 438, 'name' => 'هرسین', 'province_id' => 22, 'amar_code' => '511'],
            ['id' => 439, 'name' => 'هریس', 'province_id' => 1, 'amar_code' => '316'],
            ['id' => 440, 'name' => 'هشترود', 'province_id' => 1, 'amar_code' => '311'],
            ['id' => 441, 'name' => 'هفتکل', 'province_id' => 13, 'amar_code' => '622'],
            ['id' => 442, 'name' => 'هلیلان', 'province_id' => 6, 'amar_code' => '1611'],
            ['id' => 443, 'name' => 'همدان', 'province_id' => 30, 'amar_code' => '1304'],
            ['id' => 444, 'name' => 'هندیجان', 'province_id' => 13, 'amar_code' => '618'],
            ['id' => 445, 'name' => 'هوراند', 'province_id' => 1, 'amar_code' => '327'],
            ['id' => 446, 'name' => 'هویزه', 'province_id' => 13, 'amar_code' => '623'],
            ['id' => 447, 'name' => 'هیرمند', 'province_id' => 16, 'amar_code' => '1111'],
            ['id' => 448, 'name' => 'یزد', 'province_id' => 31, 'amar_code' => '2105'],
        ]);
    }
}