<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // درج تمام کشورها
        DB::table('countries')->insert([
            ['id' => 1, 'name' => 'افغانستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 2, 'name' => 'آلبانی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 3, 'name' => 'الجزایر', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 4, 'name' => 'آندورا', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 5, 'name' => 'آنگولا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 6, 'name' => 'آرژانتین', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 7, 'name' => 'ارمنستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 8, 'name' => 'استرالیا', 'continent_id' => 6, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 9, 'name' => 'اتریش', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 10, 'name' => 'آذربایجان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 11, 'name' => 'باهاما', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 12, 'name' => 'بحرین', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 13, 'name' => 'بنگلادش', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 14, 'name' => 'باربادوس', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 15, 'name' => 'بلاروس', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 16, 'name' => 'بلژیک', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 17, 'name' => 'بلیز', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 18, 'name' => 'بنین', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 19, 'name' => 'بوتان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 20, 'name' => 'بولیوی', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 21, 'name' => 'بوسنی و هرزگوین', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 22, 'name' => 'بوتسوانا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 23, 'name' => 'برزیل', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 24, 'name' => 'برونئی', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 25, 'name' => 'بلغارستان', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 26, 'name' => 'بورکینافاسو', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 27, 'name' => 'بوروندی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 28, 'name' => 'کامبوج', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 29, 'name' => 'کامرون', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 30, 'name' => 'کانادا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 31, 'name' => 'جمهوری آفریقای مرکزی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 32, 'name' => 'چاد', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 33, 'name' => 'شیلی', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 34, 'name' => 'چین', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 35, 'name' => 'کلمبیا', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 36, 'name' => 'کومور', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 37, 'name' => 'کنگو', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 38, 'name' => 'کاستاریکا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 39, 'name' => 'کرواسی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 40, 'name' => 'کوبا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 41, 'name' => 'قبرس', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 42, 'name' => 'جمهوری چک', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 43, 'name' => 'دانمارک', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 44, 'name' => 'جیبوتی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 45, 'name' => 'دومینیکا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 46, 'name' => 'جمهوری دومینیکن', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 47, 'name' => 'اکوادور', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 48, 'name' => 'مصر', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 49, 'name' => 'السالوادور', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 50, 'name' => 'گینه استوایی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 51, 'name' => 'اریتره', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 52, 'name' => 'استونی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 53, 'name' => 'اسواتینی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 54, 'name' => 'اتیوپی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 55, 'name' => 'فیجی', 'continent_id' => 6, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 56, 'name' => 'فنلاند', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 57, 'name' => 'فرانسه', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 58, 'name' => 'گابن', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 59, 'name' => 'گامبیا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 60, 'name' => 'گرجستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 61, 'name' => 'آلمان', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 62, 'name' => 'غنا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 63, 'name' => 'یونان', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 64, 'name' => 'گرنادا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 65, 'name' => 'گواتمالا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 66, 'name' => 'گینه', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 67, 'name' => 'گینه بیسائو', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 68, 'name' => 'هائیتی', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 69, 'name' => 'هندوراس', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 70, 'name' => 'مجارستان', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 71, 'name' => 'ایسلند', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 72, 'name' => 'هند', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 73, 'name' => 'اندونزی', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 74, 'name' => 'ایران', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 75, 'name' => 'عراق', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 76, 'name' => 'ایرلند', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 77, 'name' => 'اسرائیل', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 78, 'name' => 'ایتالیا', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 79, 'name' => 'جامائیکا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 80, 'name' => 'ژاپن', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 81, 'name' => 'اردن', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 82, 'name' => 'قزاقستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 83, 'name' => 'کنیا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 84, 'name' => 'کره شمالی', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 85, 'name' => 'کره جنوبی', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 86, 'name' => 'کویت', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 87, 'name' => 'قرقیزستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 88, 'name' => 'لائوس', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 89, 'name' => 'لتونی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 90, 'name' => 'لبنان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 91, 'name' => 'لسوتو', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 92, 'name' => 'لیبریا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 93, 'name' => 'لیبی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 94, 'name' => 'لیختن‌اشتاین', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 95, 'name' => 'لیتوانی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 96, 'name' => 'لوکزامبورگ', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 97, 'name' => 'مالاوی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 98, 'name' => 'مالزی', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 99, 'name' => 'مالدیو', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 100, 'name' => 'مالی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 101, 'name' => 'مالت', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 102, 'name' => 'موریس', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 103, 'name' => 'مکزیک', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 104, 'name' => 'مولداوی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 105, 'name' => 'موناکو', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 106, 'name' => 'مغولستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 107, 'name' => 'مونته‌نگرو', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 108, 'name' => 'مراکش', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 109, 'name' => 'موزامبیک', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 110, 'name' => 'نامیبیا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 111, 'name' => 'نپال', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 112, 'name' => 'هلند', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 113, 'name' => 'نیوزیلند', 'continent_id' => 6, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 114, 'name' => 'نیکاراگوئه', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 115, 'name' => 'نیجر', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 116, 'name' => 'نیجریه', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 117, 'name' => 'نروژ', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 118, 'name' => 'عمان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 119, 'name' => 'پاکستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 120, 'name' => 'پاناما', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 121, 'name' => 'پاپوآ گینه نو', 'continent_id' => 6, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 122, 'name' => 'پاراگوئه', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 123, 'name' => 'پرو', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 124, 'name' => 'فیلیپین', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 125, 'name' => 'لهستان', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 126, 'name' => 'پرتغال', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 127, 'name' => 'قطر', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 128, 'name' => 'روسیه', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 129, 'name' => 'رومانی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 130, 'name' => 'عربستان سعودی', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 131, 'name' => 'سنگال', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 132, 'name' => 'صربستان', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 133, 'name' => 'سنگاپور', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 134, 'name' => 'اسلواکی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 135, 'name' => 'اسلوونی', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 136, 'name' => 'آفریقای جنوبی', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 137, 'name' => 'اسپانیا', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 138, 'name' => 'سریلانکا', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 139, 'name' => 'سوئد', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 140, 'name' => 'سوئیس', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 141, 'name' => 'سوریه', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 142, 'name' => 'تاجیکستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 143, 'name' => 'تایلند', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 144, 'name' => 'تونس', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 145, 'name' => 'ترکیه', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 146, 'name' => 'ترکمنستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 147, 'name' => 'امارات متحده عربی', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 148, 'name' => 'اوکراین', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 149, 'name' => 'انگلستان', 'continent_id' => 5, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 150, 'name' => 'ایالات متحده آمریکا', 'continent_id' => 2, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 151, 'name' => 'ازبکستان', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 152, 'name' => 'ونزوئلا', 'continent_id' => 3, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 153, 'name' => 'ویتنام', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 154, 'name' => 'یمن', 'continent_id' => 4, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 155, 'name' => 'زامبیا', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 156, 'name' => 'زیمبابوه', 'continent_id' => 1, 'status' => 1, 'created_at' => null, 'updated_at' => null],
        ]);
    }
}