<!DOCTYPE html>

<html lang="fa" dir="rtl">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Ø²Ù…Ø§Ù† Ø§Ø¬Ø±Ø§ Ø¨Ù‡ Ù¾Ø§ÛŒØ§Ù† Ø±Ø³ÛŒØ¯ - EarthCoop</title>

    

    <!-- Tailwind CSS -->

    <!-- Vite CSS & JS -->

    @vite(['resources/css/app.css', 'resources/js/app.js'])

    

    <!-- FontAwesome -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

    

    <!-- Fonts -->
    <link rel="stylesheet" href="{{ asset('Css/fonts-local.css') }}">
<style>

        * {

            font-family: 'Vazirmatn', sans-serif;

        }

        

        body {

            background: linear-gradient(135deg, #f5f7fa 0%, #e8f5e9 100%);

            min-height: 100vh;

        }

        

        @keyframes pulse {

            0%, 100% { opacity: 1; }

            50% { opacity: 0.7; }

        }

        

        @keyframes bounce-custom {

            0%, 100% { transform: translateY(0); }

            50% { transform: translateY(-15px); }

        }

        

        .logo-animated {

            animation: bounce-custom 3s infinite ease-in-out;

        }

        

        .pulse-animation {

            animation: pulse 2s infinite ease-in-out;

        }

        

        @keyframes fadeIn {

            from {

                opacity: 0;

                transform: translateY(20px);

            }

            to {

                opacity: 1;

                transform: translateY(0);

            }

        }

        

        .fade-in {

            animation: fadeIn 0.6s ease-out;

        }

    </style>

</head>

<body class="font-vazirmatn leading-relaxed min-h-screen flex flex-col">

    

    <!-- Header -->

    <header class="bg-white shadow-md py-4 px-6 sticky top-0 z-50">

        <div class="container mx-auto flex items-center justify-between">

            <a href="{{ route('home') }}" class="flex items-center space-x-3 hover:opacity-80 transition-opacity">

                <svg width="45" height="45" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="logo-animated">

                    <path d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z" fill="#10b981" opacity="0.8"/>

                    <path d="M12 2C10.5 4 8 6 8 9C8 12 12 14 12 14C12 14 16 12 16 9C16 6 13.5 4 12 2ZM12 14C12 14 10 16 10 18C10 20 12 22 12 22" fill="#047857"/>

                </svg>

                <span class="text-2xl font-extrabold" style="color: #1e293b;">EarthCoop</span>

            </a>

        </div>

    </header>

    

    <!-- Main Content -->

    <main class="flex-grow flex items-center justify-center py-12 px-4">

        <div class="container mx-auto max-w-2xl">

            <div class="bg-white rounded-2xl shadow-2xl p-8 md:p-12 text-center fade-in">

                

                <!-- Icon -->

                <div class="mb-6 flex justify-center">

                    <div class="w-24 h-24 rounded-full flex items-center justify-center pulse-animation" style="background-color: #fef3c7;">

                        <i class="fas fa-clock text-5xl" style="color: #f59e0b;"></i>

                    </div>

                </div>

                

                <!-- Title -->

                <h1 class="text-3xl md:text-4xl font-extrabold mb-4" style="color: #1e293b;">

                    Ø²Ù…Ø§Ù† Ø§Ø¬Ø±Ø§ Ø¨Ù‡ Ù¾Ø§ÛŒØ§Ù† Ø±Ø³ÛŒØ¯

                </h1>

                

                <!-- Description -->

                <p class="text-lg md:text-xl text-gray-600 mb-8 leading-relaxed">

                    Ù…ØªØ£Ø³ÙØ§Ù†Ù‡ Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ø´Ù…Ø§ Ø¨ÛŒØ´ Ø§Ø² Ø­Ø¯ Ø§Ù†ØªØ¸Ø§Ø± Ø·ÙˆÙ„ Ú©Ø´ÛŒØ¯ Ùˆ Ø²Ù…Ø§Ù† Ø§Ø¬Ø±Ø§ Ø¨Ù‡ Ù¾Ø§ÛŒØ§Ù† Ø±Ø³ÛŒØ¯. Ø§ÛŒÙ† Ù…Ø´Ú©Ù„ Ù…Ø¹Ù…ÙˆÙ„Ø§Ù‹ Ù…ÙˆÙ‚ØªÛŒ Ø§Ø³Øª Ùˆ Ø¨Ø§ Ø§Ù†Ø¬Ø§Ù… Ø§Ù‚Ø¯Ø§Ù…Ø§Øª Ø²ÛŒØ± Ù…ÛŒâ€ŒØªÙˆØ§Ù†ÛŒØ¯ Ù…Ø´Ú©Ù„ Ø±Ø§ Ø¨Ø±Ø·Ø±Ù Ú©Ù†ÛŒØ¯.

                </p>

                

                <!-- Solutions -->

                <div class="bg-gray-50 rounded-xl p-6 mb-8 text-right">

                    <h2 class="text-xl font-bold mb-4" style="color: #1e293b;">

                        <i class="fas fa-lightbulb ml-2" style="color: #10b981;"></i>

                        Ø±Ø§Ù‡â€ŒØ­Ù„â€ŒÙ‡Ø§ÛŒ Ù¾ÛŒØ´Ù†Ù‡Ø§Ø¯ÛŒ:

                    </h2>

                    <ul class="space-y-3 text-gray-700">

                        <li class="flex items-start">

                            <i class="fas fa-check-circle mt-1 ml-3" style="color: #10b981;"></i>

                            <span>ØµÙØ­Ù‡ Ø±Ø§ <strong>Ø±ÙØ±Ø´</strong> Ú©Ù†ÛŒØ¯ (F5 ÛŒØ§ Ctrl+R)</span>

                        </li>

                        <li class="flex items-start">

                            <i class="fas fa-check-circle mt-1 ml-3" style="color: #10b981;"></i>

                            <span>Ú†Ù†Ø¯ Ù„Ø­Ø¸Ù‡ <strong>ØµØ¨Ø±</strong> Ú©Ù†ÛŒØ¯ Ùˆ Ø¯ÙˆØ¨Ø§Ø±Ù‡ ØªÙ„Ø§Ø´ Ú©Ù†ÛŒØ¯</span>

                        </li>

                        <li class="flex items-start">

                            <i class="fas fa-check-circle mt-1 ml-3" style="color: #10b981;"></i>

                            <span>Ø§Ú¯Ø± Ù…Ø´Ú©Ù„ Ø§Ø¯Ø§Ù…Ù‡ Ø¯Ø§Ø´ØªØŒ Ø¨Ù‡ <strong>ØµÙØ­Ù‡ Ø§ØµÙ„ÛŒ</strong> Ø¨Ø±Ú¯Ø±Ø¯ÛŒØ¯</span>

                        </li>

                        <li class="flex items-start">

                            <i class="fas fa-check-circle mt-1 ml-3" style="color: #10b981;"></i>

                            <span>Ø¯Ø± ØµÙˆØ±Øª Ù†ÛŒØ§Ø² Ø¨Ø§ <strong>Ù¾Ø´ØªÛŒØ¨Ø§Ù†ÛŒ</strong> ØªÙ…Ø§Ø³ Ø¨Ú¯ÛŒØ±ÛŒØ¯</span>

                        </li>

                    </ul>

                </div>

                

                <!-- Actions -->

                <div class="flex flex-col sm:flex-row gap-4 justify-center">

                    <a href="{{ route('home') }}" 

                       class="px-6 py-3 rounded-full text-white font-bold shadow-lg hover:shadow-xl transition duration-300 transform hover:scale-105"

                       style="background-color: #10b981;">

                        <i class="fas fa-home ml-2"></i>

                        Ø¨Ø§Ø²Ú¯Ø´Øª Ø¨Ù‡ ØµÙØ­Ù‡ Ø§ØµÙ„ÛŒ

                    </a>

                    <button onclick="window.location.reload()" 

                            class="px-6 py-3 rounded-full text-white font-bold shadow-lg hover:shadow-xl transition duration-300 transform hover:scale-105"

                            style="background-color: #3b82f6;">

                        <i class="fas fa-redo ml-2"></i>

                        ØªÙ„Ø§Ø´ Ù…Ø¬Ø¯Ø¯

                    </button>

                    @auth

                    @php

                        $supportRoute = null;

                        if (Route::has('user.tickets.create')) {

                            $supportRoute = route('user.tickets.create');

                        } elseif (Route::has('support.kb.index')) {

                            $supportRoute = route('support.kb.index');

                        } else {

                            $supportRoute = route('home');

                        }

                    @endphp

                    <a href="{{ $supportRoute }}" 

                       class="px-6 py-3 rounded-full border-2 font-bold shadow-lg hover:shadow-xl transition duration-300 transform hover:scale-105"

                       style="border-color: #f59e0b; color: #f59e0b;">

                        <i class="fas fa-headset ml-2"></i>

                        ØªÙ…Ø§Ø³ Ø¨Ø§ Ù¾Ø´ØªÛŒØ¨Ø§Ù†ÛŒ

                    </a>

                    @endauth

                </div>

                

                <!-- Additional Info -->

                <div class="mt-8 pt-6 border-t border-gray-200">

                    <p class="text-sm text-gray-500">

                        <i class="fas fa-info-circle ml-1"></i>

                        Ø§Ú¯Ø± Ø§ÛŒÙ† Ù…Ø´Ú©Ù„ Ø¨Ù‡ Ø·ÙˆØ± Ù…Ú©Ø±Ø± Ø±Ø® Ù…ÛŒâ€ŒØ¯Ù‡Ø¯ØŒ Ù„Ø·ÙØ§Ù‹ Ø¨Ø§ ØªÛŒÙ… Ù¾Ø´ØªÛŒØ¨Ø§Ù†ÛŒ ØªÙ…Ø§Ø³ Ø¨Ú¯ÛŒØ±ÛŒØ¯.

                    </p>

                </div>

                

            </div>

        </div>

    </main>

    

    <!-- Footer -->

    <footer class="bg-white border-t border-gray-200 py-6 mt-auto">

        <div class="container mx-auto text-center text-gray-600">

            <p>&copy; {{ date('Y') }} EarthCoop. ØªÙ…Ø§Ù… Ø­Ù‚ÙˆÙ‚ Ù…Ø­ÙÙˆØ¸ Ø§Ø³Øª.</p>

        </div>

    </footer>

    

</body>

</html>





