<?php

namespace App\Services\LocationGovernance\Import;

use Illuminate\Support\Facades\DB;
use InvalidArgumentException;
use RuntimeException;

/**
 * Isolated, neutral catalog import. Does NOT create operational Locations or governance.
 * Review file is generated by the pinned Iran 1404 converter.
 */
final class IranSettlementCatalogImporter
{
    public const SOURCE = 'IranCountryDivisions/geo_1404';
    public const SOURCE_COMMIT = '68687cf96cc1852d5d38c7283353c80829331758';
    public const EXPECTED_COUNT = 99317;
    public const SOURCE_GIT_BLOB = 'ca9f4a0d69c7c9d77e6434447c7fe123a322271e';

    private const SOURCE_HEADER = ['Id', 'ParentCountryDivisionId', 'Name', 'Code', 'DivisionType'];
    private const SOURCE_COUNTS = [0 => 1, 1 => 31, 2 => 484, 3 => 1193, 4 => 2777, 5 => 1481, 6 => 99317, 7 => 191];
    private const SOURCE_PARENT_TYPES = [0 => [], 1 => [0], 2 => [1], 3 => [2], 4 => [3], 5 => [3], 6 => [4], 7 => [5]];

    public function import(string $reviewPath, string $manifestPath, bool $apply = false, int $expectedCount = self::EXPECTED_COUNT): array
    {
        if (! is_file($reviewPath) || ! is_readable($reviewPath) || ! is_file($manifestPath)) {
            throw new InvalidArgumentException('Iran settlement review file and manifest must both exist.');
        }
        $manifest = json_decode((string) file_get_contents($manifestPath), true, 512, JSON_THROW_ON_ERROR);
        if (($manifest['source_commit'] ?? null) !== self::SOURCE_COMMIT
            || ($manifest['dataset_version'] ?? null) !== 'v2'
            || ($manifest['quarantined_settlements'] ?? null) !== $expectedCount
            || ! is_string($manifest['settlements_review_sha256'] ?? null)
            || ! hash_equals($manifest['settlements_review_sha256'], hash_file('sha256', $reviewPath))
            || ($manifest['settlement_classification']['residential_villages_verified'] ?? null) !== 0
            || ($manifest['settlement_classification']['governance_authorized'] ?? null) !== 0) {
            throw new InvalidArgumentException('Untrusted or mismatched Iran 1404 settlement manifest.');
        }

        // Preflight the WHOLE file before any write. A truncated/altered file
        // must not leave a partially imported catalog.
        $seen = [];
        $codes = [];
        $count = 0;
        $handle = fopen($reviewPath, 'rb');
        if ($handle === false) {
            throw new RuntimeException('Cannot open settlement review file.');
        }
        try {
            while (($line = fgets($handle)) !== false) {
                $row = json_decode($line, true, 512, JSON_THROW_ON_ERROR);
                $id = $row['external_id'] ?? null;
                $code = $row['provenance']['source_code'] ?? null;
                $parent = $row['parent_external_id'] ?? null;
                if (! is_string($id) || ! preg_match('/^IR-1404-[1-9][0-9]*$/D', $id)
                    || ! is_string($parent) || ! preg_match('/^IR-1404-[1-9][0-9]*$/D', $parent)
                    || ! is_string($code) || $code === '' || isset($seen[$id]) || isset($codes[$code])
                    || ($row['type'] ?? null) !== 'settlement'
                    || ($row['classification'] ?? null) !== 'unverified_settlement'
                    || ($row['metadata']['residential_eligibility'] ?? null) !== 'unverified'
                    || ($row['metadata']['is_residence_endpoint'] ?? null) !== false
                    || ($row['metadata']['importable'] ?? null) !== false
                    || ($row['metadata']['governance_authorized'] ?? null) !== false
                    || ($row['provenance']['source_commit'] ?? null) !== self::SOURCE_COMMIT
                    || ($row['provenance']['source_division_type'] ?? null) !== 6
                    || ($row['provenance']['source_row_id'] ?? null) !== (int) substr($id, strlen('IR-1404-'))
                    || ! is_string($row['canonical_name'] ?? null) || trim($row['canonical_name']) === '') {
                    throw new InvalidArgumentException('Invalid, duplicate or privileged settlement review record at line '.($count + 1));
                }
                $seen[$id] = true;
                $codes[$code] = true;
                $count++;
            }
        } finally {
            fclose($handle);
        }
        if ($count !== $expectedCount) {
            throw new InvalidArgumentException("Settlement review count mismatch: {$count} versus {$expectedCount}.");
        }

        $summary = ['validated' => $count, 'applied' => 0, 'mode' => $apply ? 'apply' : 'dry-run'];
        if (! $apply) {
            return $summary;
        }
        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException('Settlement catalog import is forbidden outside local/testing.');
        }
        $database = (string) DB::connection()->getDatabaseName();
        if (! preg_match('/(?:^|[_-])geo[_-]uat(?:$|[_-])/i', $database)
            && ! (app()->environment('testing') && ($database === ':memory:' || str_contains(strtolower($database), 'test')))) {
            throw new RuntimeException('Settlement catalog import requires a disposable geo_uat database.');
        }

        // No updates of classification: subsequent reviewed evidence is a
        // separate, authorized workflow. A changed identity is a hard conflict.
        $handle = fopen($reviewPath, 'rb');
        if ($handle === false) {
            throw new RuntimeException('Cannot reopen settlement review file.');
        }
        try {
            DB::transaction(function () use ($handle, &$summary): void {
                $batch = [];
                while (($line = fgets($handle)) !== false) {
                    $row = json_decode($line, true, 512, JSON_THROW_ON_ERROR);
                    $batch[] = [
                        'source' => self::SOURCE,
                        'dataset_version' => 'v2',
                        'external_id' => $row['external_id'],
                        'parent_external_id' => $row['parent_external_id'],
                        'source_code' => (string) $row['provenance']['source_code'],
                        'source_row_id' => (int) $row['provenance']['source_row_id'],
                        'name_fa' => $row['canonical_name'],
                        'search_name' => trim($row['canonical_name']),
                        'classification' => 'unverified_settlement',
                        'residential_eligibility' => 'unverified',
                        'governance_authorized' => false,
                        'operational_promotion_allowed' => false,
                        'provenance' => json_encode($row['provenance'], JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                    if (count($batch) === 40) {
                        $summary['applied'] += $this->insertNewBatch($batch);
                        $batch = [];
                    }
                }
                if ($batch !== []) {
                    $summary['applied'] += $this->insertNewBatch($batch);
                }
            });
        } finally {
            fclose($handle);
        }
        return $summary;
    }

    public function importPinnedSource(bool $apply = false, bool $allowProduction = false): array
    {
        $payload = $this->pinnedSourcePayload();
        $batches = [];
        $batch = [];
        $settlementCount = 0;
        $parentExternalIds = [];

        $this->walkPinnedSource($payload, function (array $sourceRow) use (&$batch, &$batches, &$settlementCount, &$parentExternalIds): void {
            if ($sourceRow['type'] !== 6) {
                return;
            }

            $settlementCount++;
            $parentExternalIds['IR-1404-'.$sourceRow['parent']] = true;
            $batch[] = $this->pinnedSettlementRow($sourceRow);

            if (count($batch) === 100) {
                $batches[] = $batch;
                $batch = [];
            }
        });

        if ($batch !== []) {
            $batches[] = $batch;
        }
        if ($settlementCount !== self::EXPECTED_COUNT) {
            throw new InvalidArgumentException('Pinned Iran 1404 settlement count mismatch.');
        }

        $missingParents = array_keys($parentExternalIds);
        if ($missingParents !== []) {
            $presentParents = DB::table('location_external_ids')
                ->join('locations', 'locations.id', '=', 'location_external_ids.location_id')
                ->join('location_types', 'location_types.id', '=', 'locations.location_type_id')
                ->where('location_external_ids.source', 'earthcoop-reference')
                ->where('location_external_ids.dataset_version', 'v2')
                ->where('locations.country_code', 'IR')
                ->where('locations.status', 'active')
                ->where('location_types.key', 'rural_district')
                ->whereIn('location_external_ids.external_id', $missingParents)
                ->pluck('location_external_ids.external_id')
                ->all();
            $missingParents = array_values(array_diff($missingParents, $presentParents));
        }
        if ($missingParents !== []) {
            throw new RuntimeException('Pinned settlement catalog requires the complete Iran 1404 v2 rural-district geography first.');
        }

        $wouldInsert = 0;
        foreach ($batches as $candidateBatch) {
            $wouldInsert += count($this->validatedNewRows($candidateBatch));
        }

        $summary = [
            'validated' => $settlementCount,
            'existing' => $settlementCount - $wouldInsert,
            'would_insert' => $wouldInsert,
            'applied' => 0,
            'mode' => $apply ? 'apply' : 'dry-run',
        ];

        if (! $apply) {
            return $summary;
        }

        $safeEnvironment = app()->environment(['local', 'testing'])
            || ($allowProduction && app()->environment('production'));
        if (! $safeEnvironment) {
            throw new RuntimeException('Pinned settlement catalog apply is not authorized in this environment.');
        }

        DB::transaction(function () use ($batches, &$summary): void {
            foreach ($batches as $candidateBatch) {
                $summary['applied'] += $this->insertNewBatch($candidateBatch);
            }
        });

        return $summary;
    }

    private function pinnedSourcePayload(): string
    {
        $sourceDir = base_path('database/reference/source/ir/1404');
        $payload = '';
        for ($part = 1; $part <= 9; $part++) {
            $path = $sourceDir.'/iran.part-'.str_pad((string) $part, 2, '0', STR_PAD_LEFT).'.csv';
            if (! is_file($path) || ! is_readable($path)) {
                throw new InvalidArgumentException('Iran 1404 source chunk is missing: '.basename($path));
            }
            $bytes = file_get_contents($path);
            if ($bytes === false) {
                throw new InvalidArgumentException('Iran 1404 source chunk cannot be read: '.basename($path));
            }
            $payload .= $bytes;
        }

        $blob = sha1('blob '.strlen($payload)."\0".$payload);
        if (! hash_equals(self::SOURCE_GIT_BLOB, $blob)) {
            throw new InvalidArgumentException('Iran 1404 source Git blob mismatch.');
        }

        return $payload;
    }

    private function walkPinnedSource(string $payload, callable $onRow): void
    {
        $stream = fopen('php://temp/maxmemory:8388608', 'w+b');
        if ($stream === false) {
            throw new RuntimeException('Cannot allocate Iran 1404 source parser.');
        }
        fwrite($stream, $payload);
        rewind($stream);

        $header = fgetcsv($stream);
        if (! is_array($header)) {
            fclose($stream);
            throw new InvalidArgumentException('Iran 1404 source header is missing.');
        }
        $header[0] = preg_replace('/^\xEF\xBB\xBF/', '', (string) $header[0]);
        if ($header !== self::SOURCE_HEADER) {
            fclose($stream);
            throw new InvalidArgumentException('Iran 1404 source header is invalid.');
        }

        $seenTypes = [];
        $seenCodes = [];
        $counts = array_fill_keys(array_keys(self::SOURCE_COUNTS), 0);
        $roots = 0;
        $line = 1;

        try {
            while (($csv = fgetcsv($stream)) !== false) {
                $line++;
                if ($csv === [null] || $csv === []) {
                    continue;
                }
                if (count($csv) !== 5) {
                    throw new InvalidArgumentException("Iran 1404 malformed CSV row at line {$line}.");
                }

                [$idRaw, $parentRaw, $nameRaw, $codeRaw, $typeRaw] = $csv;
                $id = filter_var($idRaw, FILTER_VALIDATE_INT);
                $parent = trim((string) $parentRaw) === '' ? null : filter_var($parentRaw, FILTER_VALIDATE_INT);
                $type = filter_var($typeRaw, FILTER_VALIDATE_INT);
                $name = trim((string) $nameRaw);
                $code = trim((string) $codeRaw);

                if ($id === false || $id < 1 || $type === false || ! array_key_exists($type, self::SOURCE_COUNTS) || $name === '' || $code === '') {
                    throw new InvalidArgumentException("Iran 1404 invalid identity/name/type at line {$line}.");
                }
                if ($parent !== null && $parent === false) {
                    throw new InvalidArgumentException("Iran 1404 invalid parent at line {$line}.");
                }
                if (isset($seenTypes[$id])) {
                    throw new InvalidArgumentException("Iran 1404 duplicate source ID {$id}.");
                }
                if ($parent === null) {
                    $roots++;
                    if ($type !== 0) {
                        throw new InvalidArgumentException("Iran 1404 non-country root {$id}.");
                    }
                } elseif (! isset($seenTypes[$parent]) || ! in_array($seenTypes[$parent], self::SOURCE_PARENT_TYPES[$type], true)) {
                    throw new InvalidArgumentException("Iran 1404 invalid or out-of-order parent for {$id}.");
                }
                if (in_array($type, [5, 6, 7], true)) {
                    $codeKey = $type.':'.$code;
                    if (isset($seenCodes[$codeKey])) {
                        throw new InvalidArgumentException("Iran 1404 duplicate source code {$code} for type {$type}.");
                    }
                    $seenCodes[$codeKey] = true;
                }

                $seenTypes[$id] = $type;
                $counts[$type]++;
                $onRow(['id' => $id, 'parent' => $parent, 'name' => $name, 'code' => $code, 'type' => $type]);
            }
        } finally {
            fclose($stream);
        }

        if ($roots !== 1 || $counts !== self::SOURCE_COUNTS) {
            throw new InvalidArgumentException('Iran 1404 pinned source counts are invalid.');
        }
    }

    private function pinnedSettlementRow(array $sourceRow): array
    {
        $externalId = 'IR-1404-'.$sourceRow['id'];

        return [
            'source' => self::SOURCE,
            'dataset_version' => 'v2',
            'external_id' => $externalId,
            'parent_external_id' => 'IR-1404-'.$sourceRow['parent'],
            'source_code' => (string) $sourceRow['code'],
            'source_row_id' => (int) $sourceRow['id'],
            'name_fa' => (string) $sourceRow['name'],
            'search_name' => trim((string) $sourceRow['name']),
            'classification' => 'unverified_settlement',
            'residential_eligibility' => 'unverified',
            'governance_authorized' => false,
            'operational_promotion_allowed' => false,
            'provenance' => json_encode([
                'source' => self::SOURCE,
                'source_commit' => self::SOURCE_COMMIT,
                'source_row_id' => (int) $sourceRow['id'],
                'source_code' => (string) $sourceRow['code'],
                'source_division_type' => 6,
                'dataset_year' => 1404,
            ], JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR),
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }

    private function canonicalValue(mixed $value): mixed
    {
        if (! is_array($value)) {
            return $value;
        }
        foreach ($value as $key => $item) {
            $value[$key] = $this->canonicalValue($item);
        }
        if (! array_is_list($value)) {
            ksort($value, SORT_STRING);
        }
        return $value;
    }

    private function validatedNewRows(array $batch): array
    {
        $ids = array_column($batch, 'external_id');
        $existing = DB::table('reference_settlements')
            ->where('source', self::SOURCE)->where('dataset_version', 'v2')
            ->whereIn('external_id', $ids)->get()->keyBy('external_id');
        $new = [];
        foreach ($batch as $row) {
            $prior = $existing->get($row['external_id']);
            if ($prior === null) {
                $new[] = $row;
                continue;
            }
            // Re-import is safe ONLY when source identity and protected
            // classification have not drifted. Never overwrite evidence.
            foreach (['parent_external_id', 'source_code', 'source_row_id', 'name_fa',
                'classification', 'residential_eligibility'] as $field) {
                if ((string) $prior->{$field} !== (string) $row[$field]) {
                    throw new RuntimeException('Existing settlement identity or classification changed: '.$row['external_id']);
                }
            }
            foreach (['governance_authorized', 'operational_promotion_allowed'] as $field) {
                if ((bool) $prior->{$field} !== (bool) $row[$field]) {
                    throw new RuntimeException('Existing settlement classification changed: '.$row['external_id']);
                }
            }
            if ($this->canonicalValue(json_decode((string) $prior->provenance, true)) !== $this->canonicalValue(json_decode($row['provenance'], true))) {
                throw new RuntimeException('Existing settlement provenance changed: '.$row['external_id']);
            }
        }

        return $new;
    }

    private function insertNewBatch(array $batch): int
    {
        $new = $this->validatedNewRows($batch);
        if ($new !== []) {
            DB::table('reference_settlements')->insert($new);
        }

        return count($new);
    }
}
