<?php

namespace App\Services\LocationGovernance\Import;

use Illuminate\Support\Facades\DB;
use InvalidArgumentException;
use RuntimeException;

/**
 * Isolated, neutral catalog import. Does NOT create operational Locations or governance.
 * Review file is generated by the pinned Iran 1404 converter.
 */
final class IranSettlementCatalogImporter
{
    public const SOURCE = 'IranCountryDivisions/geo_1404';
    public const SOURCE_COMMIT = '68687cf96cc1852d5d38c7283353c80829331758';
    public const EXPECTED_COUNT = 99317;

    public function import(string $reviewPath, string $manifestPath, bool $apply = false, int $expectedCount = self::EXPECTED_COUNT): array
    {
        if (! is_file($reviewPath) || ! is_readable($reviewPath) || ! is_file($manifestPath)) {
            throw new InvalidArgumentException('Iran settlement review file and manifest must both exist.');
        }
        $manifest = json_decode((string) file_get_contents($manifestPath), true, 512, JSON_THROW_ON_ERROR);
        if (($manifest['source_commit'] ?? null) !== self::SOURCE_COMMIT
            || ($manifest['dataset_version'] ?? null) !== 'v2'
            || ($manifest['quarantined_settlements'] ?? null) !== $expectedCount
            || ! is_string($manifest['settlements_review_sha256'] ?? null)
            || ! hash_equals($manifest['settlements_review_sha256'], hash_file('sha256', $reviewPath))
            || ($manifest['settlement_classification']['residential_villages_verified'] ?? null) !== 0
            || ($manifest['settlement_classification']['governance_authorized'] ?? null) !== 0) {
            throw new InvalidArgumentException('Untrusted or mismatched Iran 1404 settlement manifest.');
        }

        // Preflight the WHOLE file before any write. A truncated/altered file
        // must not leave a partially imported catalog.
        $seen = [];
        $codes = [];
        $count = 0;
        $handle = fopen($reviewPath, 'rb');
        if ($handle === false) {
            throw new RuntimeException('Cannot open settlement review file.');
        }
        try {
            while (($line = fgets($handle)) !== false) {
                $row = json_decode($line, true, 512, JSON_THROW_ON_ERROR);
                $id = $row['external_id'] ?? null;
                $code = $row['provenance']['source_code'] ?? null;
                $parent = $row['parent_external_id'] ?? null;
                if (! is_string($id) || ! preg_match('/^IR-1404-[1-9][0-9]*$/D', $id)
                    || ! is_string($parent) || ! preg_match('/^IR-1404-[1-9][0-9]*$/D', $parent)
                    || ! is_string($code) || $code === '' || isset($seen[$id]) || isset($codes[$code])
                    || ($row['type'] ?? null) !== 'settlement'
                    || ($row['classification'] ?? null) !== 'unverified_settlement'
                    || ($row['metadata']['residential_eligibility'] ?? null) !== 'unverified'
                    || ($row['metadata']['is_residence_endpoint'] ?? null) !== false
                    || ($row['metadata']['importable'] ?? null) !== false
                    || ($row['metadata']['governance_authorized'] ?? null) !== false
                    || ($row['provenance']['source_commit'] ?? null) !== self::SOURCE_COMMIT
                    || ($row['provenance']['source_division_type'] ?? null) !== 6
                    || ($row['provenance']['source_row_id'] ?? null) !== (int) substr($id, strlen('IR-1404-'))
                    || ! is_string($row['canonical_name'] ?? null) || trim($row['canonical_name']) === '') {
                    throw new InvalidArgumentException('Invalid, duplicate or privileged settlement review record at line '.($count + 1));
                }
                $seen[$id] = true;
                $codes[$code] = true;
                $count++;
            }
        } finally {
            fclose($handle);
        }
        if ($count !== $expectedCount) {
            throw new InvalidArgumentException("Settlement review count mismatch: {$count} versus {$expectedCount}.");
        }

        $summary = ['validated' => $count, 'applied' => 0, 'mode' => $apply ? 'apply' : 'dry-run'];
        if (! $apply) {
            return $summary;
        }
        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException('Settlement catalog import is forbidden outside local/testing.');
        }
        $database = (string) DB::connection()->getDatabaseName();
        if (! preg_match('/(?:^|[_-])geo[_-]uat(?:$|[_-])/i', $database)
            && ! (app()->environment('testing') && ($database === ':memory:' || str_contains(strtolower($database), 'test')))) {
            throw new RuntimeException('Settlement catalog import requires a disposable geo_uat database.');
        }

        // No updates of classification: subsequent reviewed evidence is a
        // separate, authorized workflow. A changed identity is a hard conflict.
        $handle = fopen($reviewPath, 'rb');
        if ($handle === false) {
            throw new RuntimeException('Cannot reopen settlement review file.');
        }
        try {
            DB::transaction(function () use ($handle, &$summary): void {
                $batch = [];
                while (($line = fgets($handle)) !== false) {
                    $row = json_decode($line, true, 512, JSON_THROW_ON_ERROR);
                    $batch[] = [
                        'source' => self::SOURCE,
                        'dataset_version' => 'v2',
                        'external_id' => $row['external_id'],
                        'parent_external_id' => $row['parent_external_id'],
                        'source_code' => (string) $row['provenance']['source_code'],
                        'source_row_id' => (int) $row['provenance']['source_row_id'],
                        'name_fa' => $row['canonical_name'],
                        'search_name' => trim($row['canonical_name']),
                        'classification' => 'unverified_settlement',
                        'residential_eligibility' => 'unverified',
                        'governance_authorized' => false,
                        'operational_promotion_allowed' => false,
                        'provenance' => json_encode($row['provenance'], JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                    if (count($batch) === 40) {
                        $summary['applied'] += $this->insertNewBatch($batch);
                        $batch = [];
                    }
                }
                if ($batch !== []) {
                    $summary['applied'] += $this->insertNewBatch($batch);
                }
            });
        } finally {
            fclose($handle);
        }
        return $summary;
    }

    private function canonicalValue(mixed $value): mixed
    {
        if (! is_array($value)) {
            return $value;
        }
        foreach ($value as $key => $item) {
            $value[$key] = $this->canonicalValue($item);
        }
        if (! array_is_list($value)) {
            ksort($value, SORT_STRING);
        }
        return $value;
    }

    private function insertNewBatch(array $batch): int
    {
        $ids = array_column($batch, 'external_id');
        $existing = DB::table('reference_settlements')
            ->where('source', self::SOURCE)->where('dataset_version', 'v2')
            ->whereIn('external_id', $ids)->get()->keyBy('external_id');
        $new = [];
        foreach ($batch as $row) {
            $prior = $existing->get($row['external_id']);
            if ($prior === null) {
                $new[] = $row;
                continue;
            }
            // Re-import is safe ONLY when source identity and protected
            // classification have not drifted. Never overwrite evidence.
            foreach (['parent_external_id', 'source_code', 'source_row_id', 'name_fa',
                'classification', 'residential_eligibility'] as $field) {
                if ((string) $prior->{$field} !== (string) $row[$field]) {
                    throw new RuntimeException('Existing settlement identity or classification changed: '.$row['external_id']);
                }
            }
            foreach (['governance_authorized', 'operational_promotion_allowed'] as $field) {
                if ((bool) $prior->{$field} !== (bool) $row[$field]) {
                    throw new RuntimeException('Existing settlement classification changed: '.$row['external_id']);
                }
            }
            if ($this->canonicalValue(json_decode((string) $prior->provenance, true)) !== $this->canonicalValue(json_decode($row['provenance'], true))) {
                throw new RuntimeException('Existing settlement provenance changed: '.$row['external_id']);
            }
        }
        if ($new !== []) {
            DB::table('reference_settlements')->insert($new);
        }
        return count($new);
    }
}
