@extends('layouts.unified')
@section('title', 'نجم هدا - دستیار هوشمند EarthCoop')

@push('styles')
<style>
.hoda-profile{direction:rtl;max-width:1040px;margin:0 auto;padding:1.5rem 1rem 3rem;color:#172033}.hoda-hero{position:relative;overflow:hidden;border-radius:28px;padding:2.2rem;background:linear-gradient(135deg,#0f766e 0%,#11b7a4 58%,#d7a92f 140%);color:#fff;box-shadow:0 20px 50px rgba(15,118,110,.18)}.hoda-hero__inner{position:relative;z-index:1;display:grid;grid-template-columns:150px 1fr;gap:1.6rem;align-items:center}.hoda-profile-avatar{width:138px;height:138px;border-radius:50%;object-fit:cover;border:4px solid rgba(255,255,255,.92);box-shadow:0 12px 30px rgba(0,0,0,.18);background:#e8fffa}.hoda-badge{display:inline-flex;align-items:center;gap:.45rem;padding:.42rem .78rem;border-radius:999px;background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.35);font-weight:800;font-size:.8rem}.hoda-title{margin:.7rem 0 .35rem;font-size:clamp(1.75rem,4vw,2.6rem);font-weight:900}.hoda-subtitle{margin:0 0 .7rem;opacity:.94;font-size:1.02rem}.hoda-lead{max-width:690px;margin:0;line-height:1.95;color:rgba(255,255,255,.9)}.hoda-actions{display:flex;gap:.75rem;flex-wrap:wrap;margin-top:1.15rem}.hoda-primary,.hoda-secondary{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:.7rem 1.2rem;border-radius:999px;font-weight:900}.hoda-primary{border:0;background:#fff;color:#08796e;box-shadow:0 8px 22px rgba(0,0,0,.12);cursor:pointer}.hoda-secondary{color:#fff;border:1px solid rgba(255,255,255,.5);text-decoration:none}.hoda-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:1.25rem}.hoda-card,.hoda-section{background:#fff;border:1px solid #e5e9ef;border-radius:20px;padding:1.2rem;box-shadow:0 7px 24px rgba(23,32,51,.06)}.hoda-card h2,.hoda-section h2{font-size:1.05rem;margin:0 0 .65rem;color:#0f766e;font-weight:900}.hoda-card p,.hoda-section p,.hoda-section li{color:#566174;line-height:1.95;font-size:.9rem}.hoda-section{margin-top:1.25rem}.hoda-examples{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.hoda-example{padding:.85rem 1rem;border-radius:14px;background:#f2fbf9;border:1px solid #c9eee8;color:#28625d;line-height:1.8}.hoda-transparency{background:linear-gradient(180deg,#fffdf6,#fff);border-color:#f0dfaa}.hoda-note{display:flex;gap:.7rem;align-items:flex-start;color:#6d5a24;line-height:1.9}@media(max-width:760px){.hoda-profile{padding:.8rem .65rem 2rem}.hoda-hero{padding:1.35rem 1rem;border-radius:20px}.hoda-hero__inner{grid-template-columns:1fr;text-align:center;gap:.9rem}.hoda-profile-avatar{width:112px;height:112px;margin:0 auto}.hoda-lead{margin-inline:auto}.hoda-actions{justify-content:center}.hoda-primary,.hoda-secondary{width:100%}.hoda-grid,.hoda-examples{grid-template-columns:1fr}.hoda-card,.hoda-section{border-radius:16px}}
</style>
@endpush

@section('content')
<main class="hoda-profile" aria-labelledby="najm-hoda-profile-title">
<section class="hoda-hero"><div class="hoda-hero__inner">
<img src="{{ asset('images/najm-hoda/avatar.webp') }}" alt="نجم هدا" class="hoda-profile-avatar" width="138" height="138">
<div><span class="hoda-badge"><i class="fas fa-shield-alt" aria-hidden="true"></i> هویت رسمی سامانه</span><h1 id="najm-hoda-profile-title" class="hoda-title">نجم هدا</h1><p class="hoda-subtitle">دستیار هوشمند EarthCoop</p><p class="hoda-lead">من همراه هوشمند شما در زیست‌بوم EarthCoop هستم؛ برای فهم بهتر امکانات، پیدا کردن مسیر درست، مشارکت مؤثرتر و دریافت راهنمایی متناسب با نقش و موقعیت شما.</p><div class="hoda-actions"><button type="button" class="hoda-primary" data-najm-hoda-open>گفتگو با نجم هدا</button><a href="#hoda-usage" class="hoda-secondary">راهنمای استفاده</a></div></div>
</div></section>
<div class="hoda-grid" aria-label="خدمات نجم هدا"><article class="hoda-card"><h2>راهنمای سامانه</h2><p>در پیدا کردن بخش‌ها، فهم امکانات، مراحل انجام کارها و رفع سردرگمی در EarthCoop راهنمایی‌تان می‌کنم.</p></article><article class="hoda-card"><h2>گروه‌ها و مشارکت</h2><p>در گفتگوها، نقش‌ها، جلسات و امکانات گروه متناسب با دسترسی و تنظیمات فعال به شما کمک می‌کنم.</p></article><article class="hoda-card"><h2>انتخابات و قواعد</h2><p>شیوه استفاده از ابزارهای انتخابات و مقررات ثبت‌شده در سامانه را توضیح می‌دهم؛ تصمیم و رأی همیشه متعلق به خود شماست.</p></article></div>
<section class="hoda-section"><h2>چه کارهایی می‌توانم برای شما انجام دهم؟</h2><ul><li>پاسخ به پرسش‌های کاربردی درباره صفحات، امکانات و مسیرهای EarthCoop.</li><li>راهنمایی متناسب با زمینه صفحه یا گروهی که در آن حضور دارید.</li><li>کمک به مدیران و مسئولان در فهم وضعیت‌ها و اقدام‌های مجاز، متناسب با سطح دسترسی.</li><li>توضیح قواعد و اسناد در محدوده دانشی که واقعاً در اختیار سامانه قرار گرفته است.</li><li>پیشنهاد قدم بعدی؛ اقدام‌های حساس بدون دسترسی و تأیید لازم انجام نمی‌شوند.</li></ul></section>
<section id="hoda-usage" class="hoda-section"><h2>چطور از نجم هدا استفاده کنم؟</h2><p>روی آواتار شناور نجم هدا در صفحات EarthCoop یا دکمه «گفتگو با نجم هدا» بزنید و سؤال‌تان را مستقیم بنویسید.</p><div class="hoda-examples"><div class="hoda-example">«در این صفحه باید چه کاری انجام بدهم؟»</div><div class="hoda-example">«قواعد این انتخابات چیست و قدم بعدی من کدام است؟»</div><div class="hoda-example">«در این گروه چه امکاناتی در اختیار من است؟»</div><div class="hoda-example">«این قانون یا تنظیم سامانه چه معنایی برای من دارد؟»</div></div></section>
<section class="hoda-section hoda-transparency"><h2>حریم خصوصی و شفافیت</h2><div class="hoda-note"><i class="fas fa-info-circle" aria-hidden="true"></i><div>نجم هدا یک <strong>هویت سیستمی</strong> و دستیار هوشمند EarthCoop است، نه یک حساب انسانی. ورود تعاملی به این هویت مجاز نیست. دسترسی‌ها و اقدام‌های آن تابع نقش شما، تنظیمات فعال سامانه و سیاست‌های تأیید است.</div></div></section>
</main>
<script>document.addEventListener('click',function(e){const t=e.target.closest('[data-najm-hoda-open]');if(!t)return;document.getElementById('najm-hoda-toggle')?.click();});</script>
@endsection
