@extends('layouts.admin')



@section('title', 'گزارش عملیات مالی نجم بهار')



@section('content')

<div class="container-fluid px-4 py-6" dir="rtl">

    <div class="mb-6">

        <h1 class="text-2xl font-bold text-slate-900 dark:text-white">

            <i class="fas fa-clipboard-list ml-2"></i>

            گزارش عملیات مالی نجم بهار

        </h1>

        <p class="text-slate-600 dark:text-slate-400 mt-1">ردیابی عملیات مالی گروه‌ها و مدیران</p>

    </div>



    <div class="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 p-6 mb-6">

        <form method="GET" action="{{ route('admin.najm-bahar.audit-logs.index') }}" class="grid grid-cols-1 md:grid-cols-4 gap-4">

            <div>

                <label class="block text-sm text-slate-600 dark:text-slate-400 mb-1">شناسه گروه</label>

                <input type="text" name="group_id" value="{{ $filters['group_id'] ?? '' }}"

                       class="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white">

            </div>

            <div>

                <label class="block text-sm text-slate-600 dark:text-slate-400 mb-1">از تاریخ</label>

                <input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"

                       class="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white">

            </div>

            <div>

                <label class="block text-sm text-slate-600 dark:text-slate-400 mb-1">تا تاریخ</label>

                <input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}"

                       class="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white">

            </div>

            <div>

                <label class="block text-sm text-slate-600 dark:text-slate-400 mb-1">شناسه/نام عامل</label>

                <input type="text" name="actor" value="{{ $filters['actor'] ?? '' }}"

                       class="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white">

            </div>

            <div>

                <label class="block text-sm text-slate-600 dark:text-slate-400 mb-1">نوع عملیات</label>

                <input type="text" name="action" value="{{ $filters['action'] ?? '' }}"

                       class="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white">

            </div>

            <div class="md:col-span-2">

                <label class="block text-sm text-slate-600 dark:text-slate-400 mb-1">جستجو</label>

                <input type="text" name="search" value="{{ $filters['search'] ?? '' }}"

                       class="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white">

            </div>

            <div class="md:col-span-4 flex items-center gap-3">

                <button type="submit" class="px-4 py-2 rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 transition">

                    اعمال فیلتر

                </button>

                <a href="{{ route('admin.najm-bahar.audit-logs.index') }}" class="px-4 py-2 rounded-lg bg-slate-200 text-slate-700 hover:bg-slate-300 transition">

                    پاک کردن

                </a>

                <a href="{{ route('admin.najm-bahar.audit-logs.export', request()->all()) }}" class="px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition">

                    خروجی CSV

                </a>

            </div>

        </form>

    </div>



    <div class="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 p-6">

        <div class="overflow-x-auto">

            <table class="w-full text-sm">

                <thead class="bg-slate-50 dark:bg-slate-700">

                    <tr>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">تاریخ</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">گروه</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">عامل</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">نقش</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">عملیات</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">حساب</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">حساب فرعی</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">مبلغ</th>

                        <th class="px-4 py-2 text-right text-slate-700 dark:text-slate-300">شرح</th>

                    </tr>

                </thead>

                <tbody class="divide-y divide-slate-200 dark:divide-slate-700">

                    @forelse($logs as $log)

                        @php

                            $actorName = $log->actor ? trim($log->actor->first_name . ' ' . $log->actor->last_name) : 'سیستم';

                        @endphp

                        <tr>

                            <td class="px-4 py-2">{{ \Morilog\Jalali\Jalalian::fromCarbon($log->created_at)->format('Y/m/d H:i') }}</td>

                            <td class="px-4 py-2">{{ $log->group_id ?? '-' }}</td>

                            <td class="px-4 py-2">{{ $actorName }}</td>

                            <td class="px-4 py-2">{{ $log->actor_role ?? '-' }}</td>

                            <td class="px-4 py-2">{{ $log->action }}</td>

                            <td class="px-4 py-2">{{ $log->account_number ?? '-' }}</td>

                            <td class="px-4 py-2">{{ $log->sub_account_code ? str_replace('-', '/', $log->sub_account_code) : '-' }}</td>

                            <td class="px-4 py-2">{{ $log->amount !== null ? \App\Helpers\BaharMoney::formatDecimalHtml($log->amount) : '-' }}</td>

                            <td class="px-4 py-2">{{ $log->description ?? '-' }}</td>

                        </tr>

                    @empty

                        <tr>

                            <td colspan="9" class="px-4 py-8 text-center text-slate-500">لاگی ثبت نشده است</td>

                        </tr>

                    @endforelse

                </tbody>

            </table>

        </div>

        <div class="mt-4">

            {{ $logs->links() }}

        </div>

    </div>

</div>

@endsection



