@extends('layouts.admin')
@section('title', 'قاعده جدید - مرکز ارتباطات')
@section('page-title', 'قاعده ارتباطی جدید')
@section('content')
<div class="container mx-auto max-w-4xl px-4 py-6">
    @if($errors->any())<div class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('admin.communications.automations.store') }}" class="space-y-4 rounded-xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">
        @csrf
        <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-1 block text-sm">کلید</label><input name="key" value="{{ old('key') }}" class="w-full rounded-lg border-gray-300 dark:bg-gray-900" required></div><div><label class="mb-1 block text-sm">نام</label><input name="name" value="{{ old('name') }}" class="w-full rounded-lg border-gray-300 dark:bg-gray-900" required></div></div>
        <div class="grid gap-4 md:grid-cols-3"><div><label class="mb-1 block text-sm">نوع Trigger</label><select name="trigger_type" class="w-full rounded-lg border-gray-300 dark:bg-gray-900" required><option value="event">event</option><option value="scheduled">scheduled</option><option value="conditional">conditional</option></select></div><div><label class="mb-1 block text-sm">Audience</label><select name="audience_key" class="w-full rounded-lg border-gray-300 dark:bg-gray-900" required>@foreach($audienceKeys as $key)<option value="{{ $key }}">{{ $key }}</option>@endforeach</select></div><div><label class="mb-1 block text-sm">Condition</label><select name="condition_key" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"><option value="">بدون شرط</option>@foreach($conditionKeys as $key)<option value="{{ $key }}">{{ $key }}</option>@endforeach</select></div></div>
        <div><label class="mb-1 block text-sm">شناسه کاربر مشخص</label><input type="number" min="1" name="user_ids[]" value="{{ old('user_ids.0') }}" class="w-full rounded-lg border-gray-300 dark:bg-gray-900" placeholder="فقط برای audience نوع specific.user"><p class="mt-1 text-xs text-gray-500">برای specific.user حداقل یک شناسه کاربر وارد کنید. برای سایر audienceها خالی بگذارید.</p></div>
        <div><label class="mb-1 block text-sm">Event key</label><input name="event_key" value="{{ old('event_key') }}" class="w-full rounded-lg border-gray-300 dark:bg-gray-900" placeholder="برای trigger نوع event"></div>
        <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-1 block text-sm">قالب</label><select name="communication_template_id" class="w-full rounded-lg border-gray-300 dark:bg-gray-900" required>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->key }}</option>@endforeach</select></div><div><label class="mb-1 block text-sm">فرستنده</label><select name="communication_sender_identity_id" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"><option value="">پیش‌فرض قالب</option>@foreach($senders as $sender)<option value="{{ $sender->id }}">{{ $sender->key }} — {{ $sender->email }}</option>@endforeach</select></div></div>
        <div class="grid gap-4 md:grid-cols-3"><div><label class="mb-1 block text-sm">طبقه‌بندی</label><select name="classification" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"><option value="required">required</option><option value="operational" selected>operational</option><option value="optional">optional</option></select></div><div><label class="mb-1 block text-sm">اولویت</label><input type="number" min="1" max="9" name="priority" value="{{ old('priority', 2) }}" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"></div><div><label class="mb-1 block text-sm">تاخیر (ثانیه)</label><input type="number" min="0" name="delay_seconds" value="{{ old('delay_seconds', 0) }}" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"></div></div>
        <fieldset class="rounded-lg border border-gray-200 p-4 dark:border-gray-700"><legend class="px-2 text-sm font-medium">زمان‌بندی — فقط برای scheduled</legend><div class="grid gap-4 md:grid-cols-3"><div><label class="mb-1 block text-sm">تناوب</label><select name="frequency" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"><option value="weekly">weekly</option><option value="daily">daily</option><option value="hourly">hourly</option></select></div><div><label class="mb-1 block text-sm">Interval</label><input type="number" min="1" name="schedule_definition[interval]" value="1" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"></div><div><label class="mb-1 block text-sm">Timezone</label><input name="timezone" value="Asia/Tehran" class="w-full rounded-lg border-gray-300 dark:bg-gray-900"></div></div></fieldset>
        <input type="hidden" name="is_active" value="0"><label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1"> فعال شود</label>
        <div class="flex gap-2"><button class="rounded-lg bg-gray-900 px-4 py-2 text-white">ایجاد قاعده</button><a href="{{ route('admin.communications.automations.index') }}" class="rounded-lg border border-gray-300 px-4 py-2">انصراف</a></div>
    </form>
</div>
@endsection
