@extends('layouts.admin')



@section('title', 'ویرایش قانون پرداخت')



@section('content')

<div class="container-fluid px-4 py-6" dir="rtl">

    <div class="flex items-center justify-between mb-6">

        <div>

            <h1 class="text-2xl font-bold text-slate-900 dark:text-white">

                <i class="fas fa-edit ml-2"></i>

                ویرایش قانون پرداخت

            </h1>

            <p class="text-slate-600 dark:text-slate-400 mt-1">ویرایش اطلاعات قانون پرداخت</p>

        </div>

        <a href="{{ route('admin.najm-bahar.salaries.index') }}"

           class="inline-flex items-center px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-700 transition-colors">

            <i class="fas fa-arrow-right ml-2"></i>

            بازگشت

        </a>

    </div>



    @if ($errors->any())

        <div class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-red-800 dark:text-red-200 px-4 py-3 rounded-lg mb-6">

            <ul class="list-disc list-inside">

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif



    @php

        $selectedGroupTypes = (array) old('group_types', data_get($salaryRule->meta, 'group_types', []));

        $selectedLocationLevels = (array) old('location_levels', data_get($salaryRule->meta, 'location_levels', []));

    @endphp



    <div class="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 p-6">

        <form action="{{ route('admin.najm-bahar.salaries.update', $salaryRule) }}" method="POST" class="space-y-6" id="salaryRuleForm">

            @csrf

            @method('PUT')



            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

                <div class="md:col-span-2">

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">عنوان قانون</label>

                    <input type="text" name="name" value="{{ old('name', $salaryRule->name) }}" required

                           class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                </div>



                <div>

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">نوع قانون</label>

                    <select name="rule_type" id="rule_type" required

                            class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                        <option value="role" {{ old('rule_type', $salaryRule->rule_type) === 'role' ? 'selected' : '' }}>مدیر/بازرس</option>

                        <option value="user" {{ old('rule_type', $salaryRule->rule_type) === 'user' ? 'selected' : '' }}>کارمند</option>

                        <option value="project" {{ old('rule_type', $salaryRule->rule_type) === 'project' ? 'selected' : '' }}>پروژه‌ای</option>

                    </select>

                </div>



                <div id="role_code_field">

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">نقش</label>

                    <select name="role_code"

                            class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                        <option value="">همه</option>

                        <option value="2" {{ old('role_code', $salaryRule->role_code) == 2 ? 'selected' : '' }}>بازرس</option>

                        <option value="3" {{ old('role_code', $salaryRule->role_code) == 3 ? 'selected' : '' }}>مدیر</option>

                    </select>

                </div>



                <div id="group_type_field">

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">نوع گروه</label>

                    <div class="grid grid-cols-1 sm:grid-cols-3 gap-2">

                        @foreach($groupTypeOptions as $value => $label)

                            <label class="flex items-center gap-2 text-sm text-slate-700 dark:text-slate-300">

                                <input type="checkbox" name="group_types[]" value="{{ $value }}" {{ in_array($value, $selectedGroupTypes, true) ? 'checked' : '' }}

                                       class="w-4 h-4 text-blue-600 border-slate-300 rounded focus:ring-blue-500">

                                <span>{{ $label }}</span>

                            </label>

                        @endforeach

                    </div>

                    <p class="text-xs text-slate-500 dark:text-slate-400 mt-1">اگر انتخاب نکنید، شامل همه نوع گروه‌ها می‌شود.</p>

                </div>



                <div id="location_level_field">

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">سطح مکانی</label>

                    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">

                        @foreach($locationLevelOptions as $value => $label)

                            <label class="flex items-center gap-2 text-sm text-slate-700 dark:text-slate-300">

                                <input type="checkbox" name="location_levels[]" value="{{ $value }}" {{ in_array($value, $selectedLocationLevels, true) ? 'checked' : '' }}

                                       class="w-4 h-4 text-blue-600 border-slate-300 rounded focus:ring-blue-500">

                                <span>{{ $label }}</span>

                            </label>

                        @endforeach

                    </div>

                    <p class="text-xs text-slate-500 dark:text-slate-400 mt-1">در صورت نیاز می‌توانید چند سطح را همزمان انتخاب کنید.</p>

                </div>



                <div id="user_id_field">

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">کاربر</label>

                    <select name="user_id"

                            class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                        <option value="">انتخاب کاربر</option>

                        @foreach($users as $user)

                            <option value="{{ $user->id }}" {{ old('user_id', $salaryRule->user_id) == $user->id ? 'selected' : '' }}>{{ trim($user->first_name . ' ' . $user->last_name) }}</option>

                        @endforeach

                    </select>

                </div>



                <div id="project_id_field">

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">شناسه پروژه</label>

                    <input type="text" name="project_id" value="{{ old('project_id', $salaryRule->project_id) }}"

                           class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                </div>



                <div>

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">مبلغ (بهار.گل)</label>

                          <input type="text" name="amount" value="{{ old('amount', \App\Helpers\BaharMoney::formatDecimalValue($salaryRule->amount_gol)) }}" required

                           class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                </div>



                <div>

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">زمان‌بندی</label>

                    <select name="schedule_type" id="schedule_type" required

                            class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                        <option value="monthly" {{ old('schedule_type', $salaryRule->schedule_type) === 'monthly' ? 'selected' : '' }}>ماهانه</option>

                        <option value="interval" {{ old('schedule_type', $salaryRule->schedule_type) === 'interval' ? 'selected' : '' }}>دوره‌ای</option>

                        <option value="one_time" {{ old('schedule_type', $salaryRule->schedule_type) === 'one_time' ? 'selected' : '' }}>یک‌باره</option>

                    </select>

                </div>



                <div id="interval_days_field">

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">فاصله دوره‌ای (روز)</label>

                    <input type="number" name="interval_days" value="{{ old('interval_days', $salaryRule->interval_days) }}" min="1"

                           class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                </div>



                <div>

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">شروع</label>

                    <input type="date" name="start_at" value="{{ old('start_at', optional($salaryRule->start_at)->format('Y-m-d')) }}"

                           class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                </div>



                <div>

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">پایان</label>

                    <input type="date" name="end_at" value="{{ old('end_at', optional($salaryRule->end_at)->format('Y-m-d')) }}"

                           class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                </div>



                <div>

                    <label class="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">حداقل امتیاز فعالیت</label>

                    <input type="number" name="min_activity_score" value="{{ old('min_activity_score', $salaryRule->min_activity_score) }}" min="0"

                           class="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-slate-700 dark:text-white">

                </div>



                <div class="md:col-span-2">

                    <label class="flex items-center">

                        <input type="checkbox" name="requires_senior_approval" value="1" {{ old('requires_senior_approval', $salaryRule->requires_senior_approval) ? 'checked' : '' }}

                               class="w-4 h-4 text-blue-600 border-slate-300 rounded focus:ring-blue-500">

                        <span class="mr-2 text-sm font-semibold text-slate-700 dark:text-slate-300">نیاز به تایید مدیر ارشد</span>

                    </label>

                </div>



                <div class="md:col-span-2">

                    <label class="flex items-center">

                        <input type="checkbox" name="is_active" value="1" {{ old('is_active', $salaryRule->is_active) ? 'checked' : '' }}

                               class="w-4 h-4 text-blue-600 border-slate-300 rounded focus:ring-blue-500">

                        <span class="mr-2 text-sm font-semibold text-slate-700 dark:text-slate-300">قانون فعال است</span>

                    </label>

                </div>

            </div>



            <div class="flex items-center justify-end space-x-3 space-x-reverse pt-4 border-t border-slate-200 dark:border-slate-700">

                <a href="{{ route('admin.najm-bahar.salaries.index') }}" class="inline-flex items-center px-6 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-700 transition-colors">

                    انصراف

                </a>

                <button type="submit" class="inline-flex items-center px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors">

                    ذخیره تغییرات

                </button>

            </div>

        </form>

    </div>

</div>



@push('scripts')

<script>

function toggleSalaryFields() {

    const ruleType = document.getElementById('rule_type').value;

    const scheduleType = document.getElementById('schedule_type').value;



    document.getElementById('role_code_field').style.display = ruleType === 'role' ? 'block' : 'none';

    document.getElementById('group_type_field').style.display = ruleType === 'role' ? 'block' : 'none';

    document.getElementById('location_level_field').style.display = ruleType === 'role' ? 'block' : 'none';

    document.getElementById('user_id_field').style.display = ruleType === 'user' || ruleType === 'project' ? 'block' : 'none';

    document.getElementById('project_id_field').style.display = ruleType === 'project' ? 'block' : 'none';

    document.getElementById('interval_days_field').style.display = scheduleType === 'interval' ? 'block' : 'none';

}



document.addEventListener('DOMContentLoaded', function () {

    toggleSalaryFields();

    document.getElementById('rule_type').addEventListener('change', toggleSalaryFields);

    document.getElementById('schedule_type').addEventListener('change', toggleSalaryFields);

});

</script>

@endpush

@endsection



