@extends('layouts.unified')



@section('title', 'پرداخت سرمایه‌گذاری - نجم بهار')



@section('content')

<div class="container mx-auto px-4 py-8" dir="rtl">

    <div class="mb-8">

        <h1 class="text-3xl font-bold text-gray-900">پرداخت سرمایه‌گذاری</h1>

        <p class="text-gray-600 mt-2">لطفا پرداخت خود را تکمیل کنید.</p>

    </div>



    <div class="bg-white rounded-lg shadow p-6 max-w-xl">

        <div class="space-y-3 text-sm">

            <div class="flex justify-between">

                <span class="text-gray-600">پروژه:</span>

                <span class="font-semibold">{{ $investment->project->title }}</span>

            </div>

            <div class="flex justify-between">

                <span class="text-gray-600">مبلغ:</span>

                <span class="font-semibold">{{ number_format($investment->amount) }} گل</span>

            </div>

            <div class="flex justify-between">

                <span class="text-gray-600">درصد سود:</span>

                <span class="font-semibold text-green-600">{{ $investment->agreed_profit_percentage ?? $investment->project->profit_percentage }}%</span>

            </div>

        </div>



        <form method="POST" action="{{ route('najm-bahar.investments.process-payment', $investment) }}" class="mt-6">

            @csrf

            <label class="block text-sm font-medium text-gray-700 mb-2">کد پیگیری (اختیاری)</label>

            <input type="text" name="tracking_code" class="w-full rounded-lg border-gray-300" placeholder="اختیاری">

            <button type="submit" class="mt-4 w-full px-6 py-3 bg-green-600 hover:bg-green-700 text-white rounded-lg">

                پرداخت و فعال‌سازی

            </button>

        </form>

    </div>

</div>

@endsection

